# Generated by Django 4.2.9 on 2025-11-24 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0001_initial'),
        ('sales', '0001_initial'),
        ('projects', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='货币代码')),
                ('name', models.CharField(max_length=50, verbose_name='货币名称')),
                ('symbol', models.CharField(max_length=5, verbose_name='货币符号')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=12, verbose_name='汇率（相对于基准货币）')),
                ('is_base_currency', models.BooleanField(default=False, verbose_name='是否为基准货币')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '货币',
                'verbose_name_plural': '货币',
                'db_table': 'currency',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='accountpayable',
            options={'ordering': ['-invoice_date'], 'verbose_name': '应付账款', 'verbose_name_plural': '应付账款'},
        ),
        migrations.AlterModelOptions(
            name='accountreceivable',
            options={'ordering': ['-invoice_date'], 'verbose_name': '应收账款', 'verbose_name_plural': '应收账款'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date'], 'verbose_name': '费用', 'verbose_name_plural': '费用'},
        ),
        migrations.RemoveField(
            model_name='accountpayable',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='accountreceivable',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='notes',
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=12, verbose_name='汇率'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=12, verbose_name='汇率'),
        ),
        migrations.AddField(
            model_name='expense',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='基准货币金额'),
        ),
        migrations.AddField(
            model_name='expense',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=12, verbose_name='汇率（记录时）'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='due_date',
            field=models.DateField(verbose_name='到期日'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='invoice_date',
            field=models.DateField(verbose_name='发票日期'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='发票号'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='purchase.purchaseorder', verbose_name='采购订单'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='due_date',
            field=models.DateField(verbose_name='到期日'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='invoice_date',
            field=models.DateField(verbose_name='发票日期'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='发票号'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='projects.project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='so',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='sales.salesorder', verbose_name='销售订单'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('TRAVEL', '差旅费'), ('MEAL', '餐饮费'), ('OFFICE', '办公用品'), ('COMMUNICATION', '通讯费'), ('TRAINING', '培训费'), ('OTHER', '其他')], max_length=20, verbose_name='费用类别'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounts.department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='费用编号'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='projects.project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('PAID', '已支付')], default='DRAFT', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('payment_no', models.CharField(max_length=50, unique=True, verbose_name='付款单号')),
                ('payment_type', models.CharField(choices=[('AR', '应收款'), ('AP', '应付款')], max_length=10, verbose_name='付款类型')),
                ('payment_date', models.DateField(verbose_name='付款日期')),
                ('payment_method', models.CharField(choices=[('CASH', '现金'), ('BANK_TRANSFER', '银行转账'), ('CREDIT_CARD', '信用卡'), ('CHECK', '支票'), ('OTHER', '其他')], max_length=20, verbose_name='付款方式')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='付款金额')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=12, verbose_name='汇率')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('ap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.accountpayable', verbose_name='应付账款')),
                ('ar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.accountreceivable', verbose_name='应收账款')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.currency', verbose_name='货币')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '付款记录',
                'verbose_name_plural': '付款记录',
                'db_table': 'payment',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='finance.currency', verbose_name='货币'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='finance.currency', verbose_name='货币'),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.currency', verbose_name='货币'),
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='汇率')),
                ('effective_date', models.DateField(db_index=True, verbose_name='生效日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='finance.currency', verbose_name='货币')),
            ],
            options={
                'verbose_name': '汇率历史',
                'verbose_name_plural': '汇率历史',
                'db_table': 'exchange_rate_history',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['currency', '-effective_date'], name='exchange_ra_currenc_2d4d58_idx')],
            },
        ),
    ]
