# Generated by Django 4.2.9 on 2025-11-25 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_timelog'),
        ('finance', '0002_currency_alter_accountpayable_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('expense_no', models.CharField(max_length=50, unique=True, verbose_name='费用编号')),
                ('name', models.CharField(max_length=200, verbose_name='费用名称')),
                ('category', models.CharField(choices=[('RENT', '房租'), ('UTILITIES', '水电费'), ('EQUIPMENT', '设备折旧'), ('IT', 'IT服务'), ('ADMIN', '行政费用'), ('INSURANCE', '保险费'), ('DEPRECIATION', '折旧'), ('OTHER', '其他')], max_length=20, verbose_name='费用类别')),
                ('description', models.TextField(blank=True, verbose_name='费用说明')),
                ('expense_date', models.DateField(verbose_name='费用日期')),
                ('period_start', models.DateField(verbose_name='分摊期间开始')),
                ('period_end', models.DateField(verbose_name='分摊期间结束')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='费用金额')),
                ('allocation_method', models.CharField(choices=[('EQUAL', '平均分摊'), ('REVENUE', '按收入比例'), ('HEADCOUNT', '按人员数量'), ('LABOR_HOURS', '按工时比例'), ('BUDGET', '按预算比例'), ('CUSTOM', '自定义比例')], default='EQUAL', max_length=20, verbose_name='分摊方式')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待分摊'), ('ALLOCATED', '已分摊'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('allocated_at', models.DateTimeField(blank=True, null=True, verbose_name='分摊时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_shared_expenses', to=settings.AUTH_USER_MODEL, verbose_name='分摊人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '公共费用',
                'verbose_name_plural': '公共费用',
                'db_table': 'shared_expense',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='SharedExpenseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('allocation_ratio', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='分摊比例')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='分摊金额')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_expense_allocations', to='projects.project', verbose_name='项目')),
                ('shared_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.sharedexpense', verbose_name='公共费用')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '费用分摊明细',
                'verbose_name_plural': '费用分摊明细',
                'db_table': 'shared_expense_allocation',
                'unique_together': {('shared_expense', 'project')},
            },
        ),
    ]
