# Generated by Django 4.2.9 on 2025-12-30 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0010_add_purchase_payment_schedule'),
    ]

    operations = [
        # Add missing fields to payment schedules
        migrations.AddField(
            model_name='paymentschedule',
            name='bank_statements',
            field=models.ManyToManyField(blank=True, related_name='payment_schedules', to='finance.bankstatement', verbose_name='关联银行流水'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='purchasepaymentschedule',
            name='bank_statements',
            field=models.ManyToManyField(blank=True, related_name='purchase_payment_schedules', to='finance.bankstatement', verbose_name='关联银行流水'),
        ),
        migrations.AddField(
            model_name='purchasepaymentschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='purchasepaymentschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
    ]

