# Generated by Django 4.2.9 on 2025-11-23 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('adjustment_no', models.CharField(max_length=50, unique=True, verbose_name='调整单号')),
                ('adjustment_date', models.DateField(verbose_name='调整日期')),
                ('reason', models.TextField(verbose_name='调整原因')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('CONFIRMED', '已确认')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='masterdata.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存调整',
                'verbose_name_plural': '库存调整',
                'db_table': 'stock_adjustment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('move_no', models.CharField(max_length=50, unique=True, verbose_name='移动单号')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='数量')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='单位成本')),
                ('move_type', models.CharField(choices=[('IN_PURCHASE', '采购入库'), ('OUT_SALES', '销售出库'), ('OUT_PROJECT', '项目领料'), ('TRANSFER', '调拨'), ('ADJUSTMENT', '调整')], max_length=20, verbose_name='移动类型')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='参考类型')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='参考ID')),
                ('move_date', models.DateField(verbose_name='移动日期')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('COMPLETED', '完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='masterdata.item', verbose_name='物料')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves', to='projects.project', verbose_name='关联项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('warehouse_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves_out', to='masterdata.warehouse', verbose_name='来源仓库')),
                ('warehouse_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves_in', to='masterdata.warehouse', verbose_name='目标仓库')),
            ],
            options={
                'verbose_name': '库存移动',
                'verbose_name_plural': '库存移动',
                'db_table': 'stock_move',
                'ordering': ['-move_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('qty_system', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='账面数量')),
                ('qty_actual', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='实际数量')),
                ('qty_diff', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='差异数量')),
                ('cost_impact', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='成本影响')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockadjustment', verbose_name='调整单')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_lines', to='masterdata.item', verbose_name='物料')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '库存调整明细',
                'verbose_name_plural': '库存调整明细',
                'db_table': 'stock_adjustment_line',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='账面库存')),
                ('qty_reserved', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='预留数量')),
                ('weighted_avg_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='加权平均成本')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='masterdata.item', verbose_name='物料')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='masterdata.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'db_table': 'stock',
                'ordering': ['warehouse', 'item'],
                'unique_together': {('warehouse', 'item')},
            },
        ),
    ]
