# Generated by Django 4.2.9 on 2025-11-26 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0002_remove_warehouse_location_warehouse_address_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('batch_no', models.CharField(max_length=50, verbose_name='批次号')),
                ('manufacture_date', models.DateField(blank=True, null=True, verbose_name='生产日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('qty_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='现有数量')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='单位成本')),
                ('supplier_batch_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='供应商批次号')),
                ('quality_status', models.CharField(choices=[('PENDING', '待检'), ('PASSED', '合格'), ('FAILED', '不合格'), ('QUARANTINE', '隔离')], default='PENDING', max_length=20, verbose_name='质量状态')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='masterdata.item', verbose_name='物料')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='masterdata.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '批次',
                'verbose_name_plural': '批次',
                'db_table': 'batch',
                'ordering': ['expiry_date', '-manufacture_date'],
            },
        ),
        migrations.CreateModel(
            name='BatchMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('move_type', models.CharField(choices=[('IN', '入库'), ('OUT', '出库'), ('ADJUST', '调整'), ('TRANSFER', '调拨')], max_length=20, verbose_name='移动类型')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='数量')),
                ('reference_type', models.CharField(max_length=50, verbose_name='参考类型')),
                ('reference_id', models.IntegerField(verbose_name='参考ID')),
                ('move_date', models.DateTimeField(auto_now_add=True, verbose_name='移动时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='inventory.batch', verbose_name='批次')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '批次移动',
                'verbose_name_plural': '批次移动',
                'db_table': 'batch_move',
                'ordering': ['-move_date'],
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['item', 'warehouse'], name='batch_item_id_c6f35d_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['expiry_date'], name='batch_expiry__3e6c1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('batch_no', 'item', 'warehouse')},
        ),
    ]
