# Generated by Django 4.2.9 on 2026-07-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_datavalidationresult_datavalidationrule_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['-move_date'], name='stock_move_move_da_858769_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['status', 'move_type'], name='stock_move_status_37bc8f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['reference_type', 'reference_id'], name='stock_move_referen_838aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['item', '-move_date'], name='stock_move_item_id_333292_idx'),
        ),
    ]
