# Generated by Django 4.2.9 on 2026-07-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockmove_stock_move_move_da_858769_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_no',
            field=models.CharField(max_length=50, verbose_name='调整单号'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='move_no',
            field=models.CharField(max_length=50, verbose_name='移动单号'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('adjustment_no',), name='uq_stock_adjustment_adjustment_no_active'),
        ),
        migrations.AddConstraint(
            model_name='stockmove',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('move_no',), name='uq_stock_move_move_no_active'),
        ),
    ]
