# Generated by Django 4.2.9 on 2026-01-13
# Initial migration for production app

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_requirementreview_reviewtemplate_reviewcheckitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='工作中心编码')),
                ('name', models.CharField(max_length=200, verbose_name='工作中心名称')),
                ('work_center_type', models.CharField(choices=[('MACHINE', '机加工中心'), ('ASSEMBLY', '装配工位'), ('WELDING', '焊接工位'), ('WIRING', '布线工位'), ('TESTING', '测试工位'), ('PAINTING', '喷涂工位'), ('PACKAGING', '包装工位'), ('OTHER', '其他')], default='ASSEMBLY', max_length=20, verbose_name='工作中心类型')),
                ('capacity_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=10, verbose_name='日产能(小时)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '工作中心',
                'verbose_name_plural': '工作中心',
                'db_table': 'mes_work_center',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('process_no', models.CharField(max_length=50, verbose_name='工序编号')),
                ('name', models.CharField(max_length=200, verbose_name='工序名称')),
                ('process_type', models.CharField(choices=[('MACHINING', '机加工'), ('WELDING', '焊接'), ('ASSEMBLY', '装配'), ('WIRING', '布线'), ('PROGRAMMING', '编程调试'), ('TESTING', '测试'), ('PAINTING', '喷涂'), ('PACKAGING', '包装'), ('OTHER', '其他')], default='ASSEMBLY', max_length=20, verbose_name='工序类型')),
                ('sequence', models.IntegerField(default=1, verbose_name='工序顺序')),
                ('planned_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='计划工时(小时)')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际工时(小时)')),
                ('work_center', models.CharField(blank=True, max_length=100, verbose_name='工作中心')),
                ('description', models.TextField(blank=True, verbose_name='工序说明')),
                ('work_instruction', models.TextField(blank=True, verbose_name='作业指导书')),
                ('quality_requirements', models.TextField(blank=True, verbose_name='质量要求')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_processes', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_processes', to='projects.project', verbose_name='所属项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('bom_items', models.ManyToManyField(blank=True, related_name='processes', to='projects.projectbom', verbose_name='所需物料')),
            ],
            options={
                'verbose_name': '生产工序',
                'verbose_name_plural': '生产工序',
                'db_table': 'production_process',
                'ordering': ['project', 'sequence'],
                'unique_together': {('project', 'process_no')},
            },
        ),
    ]
