# Generated by Django 5.2.16 on 2026-07-29 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_andoncall_assemblyguide_assemblystep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='componentbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('child_sn',), name='uniq_active_binding_per_child_sn'),
        ),
    ]
