# Generated by Django 4.2.9 on 2025-12-23 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0002_remove_warehouse_location_warehouse_address_and_more'),
        ('sales', '0001_initial'),
        ('projects', '0002_timelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('ecn_no', models.CharField(max_length=50, unique=True, verbose_name='变更编号')),
                ('title', models.CharField(max_length=200, verbose_name='变更标题')),
                ('change_type', models.CharField(choices=[('DESIGN', '设计变更'), ('PROCESS', '工艺变更'), ('MATERIAL', '材料替换'), ('SPEC', '规格变更'), ('DRAWING', '图纸变更'), ('OTHER', '其他变更')], default='DESIGN', max_length=20, verbose_name='变更类型')),
                ('priority', models.CharField(choices=[('URGENT', '紧急'), ('HIGH', '高'), ('MEDIUM', '中'), ('LOW', '低')], default='MEDIUM', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待评审'), ('REVIEWING', '评审中'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('IMPLEMENTING', '实施中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('reason', models.TextField(verbose_name='变更原因')),
                ('description', models.TextField(verbose_name='变更描述')),
                ('impact_analysis', models.TextField(blank=True, verbose_name='影响分析')),
                ('cost_impact', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='成本影响')),
                ('schedule_impact', models.CharField(blank=True, max_length=200, verbose_name='进度影响')),
                ('requested_date', models.DateField(verbose_name='申请日期')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='批准日期')),
                ('implemented_date', models.DateField(blank=True, null=True, verbose_name='实施日期')),
                ('implementation_notes', models.TextField(blank=True, verbose_name='实施说明')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ecns', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('implemented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implemented_ecns', to=settings.AUTH_USER_MODEL, verbose_name='实施人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecns', to='projects.project', verbose_name='项目')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_ecns', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '工程变更通知',
                'verbose_name_plural': '工程变更通知',
                'db_table': 'project_ecn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ECNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('change_type', models.CharField(choices=[('ADD', '新增'), ('DELETE', '删除'), ('MODIFY', '修改'), ('REPLACE', '替换')], default='MODIFY', max_length=20, verbose_name='变更类型')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='变更字段')),
                ('old_value', models.TextField(blank=True, verbose_name='原值')),
                ('new_value', models.TextField(blank=True, verbose_name='新值')),
                ('old_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='原数量')),
                ('new_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='新数量')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('bom_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecn_items', to='projects.projectbom', verbose_name='BOM条目')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('ecn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.ecn', verbose_name='ECN')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecn_items', to='masterdata.item', verbose_name='物料')),
                ('new_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecn_new_items', to='masterdata.item', verbose_name='新物料（替换时使用）')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'ECN变更明细',
                'verbose_name_plural': 'ECN变更明细',
                'db_table': 'project_ecn_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ECNApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('action', models.CharField(choices=[('SUBMIT', '提交评审'), ('APPROVE', '批准'), ('REJECT', '拒绝'), ('RETURN', '退回修改'), ('IMPLEMENT', '开始实施'), ('COMPLETE', '完成实施'), ('CANCEL', '取消')], max_length=20, verbose_name='操作')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecn_approvals', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('ecn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='projects.ecn', verbose_name='ECN')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'ECN审批记录',
                'verbose_name_plural': 'ECN审批记录',
                'db_table': 'project_ecn_approval',
                'ordering': ['-created_at'],
            },
        ),
    ]

