# Generated by Django 4.2.9 on 2025-12-24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0001_initial'),
        ('projects', '0003_ecn_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='工单编号')),
                ('order_type', models.CharField(choices=[('WARRANTY', '保修服务'), ('REPAIR', '维修服务'), ('MAINTENANCE', '保养维护'), ('UPGRADE', '升级改造'), ('TRAINING', '培训服务'), ('INSPECTION', '巡检服务'), ('COMPLAINT', '客户投诉'), ('OTHER', '其他')], default='REPAIR', max_length=20, verbose_name='工单类型')),
                ('priority', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高'), ('URGENT', '紧急')], default='MEDIUM', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('ASSIGNED', '已派单'), ('IN_PROGRESS', '处理中'), ('ON_SITE', '现场服务'), ('WAITING_PARTS', '等待备件'), ('RESOLVED', '已解决'), ('CLOSED', '已关闭'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='状态')),
                ('title', models.CharField(max_length=200, verbose_name='问题标题')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('equipment_info', models.CharField(blank=True, max_length=500, verbose_name='设备信息')),
                ('fault_code', models.CharField(blank=True, max_length=50, verbose_name='故障代码')),
                ('contact_person', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('site_address', models.CharField(blank=True, max_length=500, verbose_name='现场地址')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='报修时间')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='期望完成日期')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('is_warranty', models.BooleanField(default=True, verbose_name='是否保修期内')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='人工费用')),
                ('travel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='差旅费用')),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='备件费用')),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='其他费用')),
                ('solution', models.TextField(blank=True, verbose_name='解决方案')),
                ('root_cause', models.TextField(blank=True, verbose_name='根本原因')),
                ('preventive_action', models.TextField(blank=True, verbose_name='预防措施')),
                ('satisfaction_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='满意度评分(1-5)')),
                ('customer_feedback', models.TextField(blank=True, verbose_name='客户反馈')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_aftersales', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aftersales_orders', to='masterdata.customer', verbose_name='客户')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aftersales_orders', to='projects.project', verbose_name='关联项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '售后工单',
                'verbose_name_plural': '售后工单',
                'db_table': 'aftersales_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('service_type', models.CharField(choices=[('REMOTE', '远程支持'), ('ON_SITE', '现场服务'), ('PHONE', '电话支持'), ('VIDEO', '视频会议')], default='ON_SITE', max_length=20, verbose_name='服务类型')),
                ('service_date', models.DateField(verbose_name='服务日期')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='结束时间')),
                ('work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='工时(小时)')),
                ('work_content', models.TextField(verbose_name='工作内容')),
                ('findings', models.TextField(blank=True, verbose_name='现场发现')),
                ('actions_taken', models.TextField(blank=True, verbose_name='采取措施')),
                ('result', models.TextField(blank=True, verbose_name='服务结果')),
                ('next_steps', models.TextField(blank=True, verbose_name='后续计划')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='人工费用')),
                ('travel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='差旅费用')),
                ('customer_signature', models.CharField(blank=True, max_length=100, verbose_name='客户签字')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='签字时间')),
                ('aftersales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='projects.aftersalesorder', verbose_name='售后工单')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_records', to=settings.AUTH_USER_MODEL, verbose_name='服务人员')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '服务记录',
                'verbose_name_plural': '服务记录',
                'db_table': 'aftersales_service_record',
                'ordering': ['-service_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SparePartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('is_warranty', models.BooleanField(default=True, verbose_name='保修范围')),
                ('is_replaced', models.BooleanField(default=True, verbose_name='是否更换')),
                ('serial_no', models.CharField(blank=True, max_length=100, verbose_name='序列号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('aftersales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='projects.aftersalesorder', verbose_name='售后工单')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spare_part_usages', to='masterdata.item', verbose_name='备件')),
                ('service_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts', to='projects.servicerecord', verbose_name='服务记录')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '备件使用记录',
                'verbose_name_plural': '备件使用记录',
                'db_table': 'aftersales_spare_part_usage',
                'ordering': ['-created_at'],
            },
        ),
    ]

