# Generated by Django 4.2.9 on 2026-01-14 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_automation_bom_fields'),
        ('projects', '0009_automation_bom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbom',
            name='price_with_tax',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='含税单价'),
        ),
        migrations.AddField(
            model_name='projectbom',
            name='price_without_tax',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='未税单价'),
        ),
        migrations.AddField(
            model_name='projectbom',
            name='quote_date',
            field=models.DateField(blank=True, null=True, verbose_name='询价日期'),
        ),
        migrations.AddField(
            model_name='projectbom',
            name='quote_delivery_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='报价交期(天)'),
        ),
        migrations.AddField(
            model_name='projectbom',
            name='quote_notes',
            field=models.TextField(blank=True, verbose_name='询价备注'),
        ),
        migrations.AddField(
            model_name='projectbom',
            name='quote_status',
            field=models.CharField(choices=[('NOT_QUOTED', '未询价'), ('QUOTING', '询价中'), ('QUOTED', '已询价')], default='NOT_QUOTED', max_length=20, verbose_name='询价状态'),
        ),
        migrations.AddField(
            model_name='projectbom',
            name='quote_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_bom_items', to='masterdata.supplier', verbose_name='询价供应商'),
        ),
        migrations.AddField(
            model_name='projectbom',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='如13表示13%', max_digits=5, null=True, verbose_name='税率(%)'),
        ),
    ]
