# Generated by Django 4.2.9 on 2026-06-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_acceptance_acceptancecheckitem_acceptanceissue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='drawings/%Y/%m/', verbose_name='图纸文件'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='文件路径'),
        ),
    ]
