# Generated by Django 4.2.9 on 2026-06-15 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_drawing_file_alter_drawing_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='projects.project', verbose_name='所属项目'),
        ),
    ]
