# Generated by Django 4.2.9 on 2026-07-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_drawing_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, help_text='项目整体进度%', max_digits=5, verbose_name='项目整体进度'),
        ),
    ]
