# Generated by Django 4.2.9 on 2026-07-09 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0016_project_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbom',
            name='bom_type',
            field=models.CharField(choices=[('DESIGN', '设计BOM'), ('ENGINEERING', '工程BOM(EBOM)'), ('MANUFACTURING', '制造BOM(MBOM)')], default='ENGINEERING', help_text='EBOM/MBOM 分离基础;完整多类型结构化 BOM 与转换为后续里程碑', max_length=20, verbose_name='BOM类型'),
        ),
        migrations.CreateModel(
            name='StageGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('gate_no', models.CharField(blank=True, max_length=50, unique=True, verbose_name='评审编号')),
                ('stage', models.CharField(choices=[('CHARTER', '立项 (Charter)'), ('ES', '概念/需求 (ES)'), ('EVT', '工程验证 (EVT)'), ('DVT', '设计验证 (DVT)'), ('PVT', '生产验证 (PVT)'), ('MP', '量产 (MP)'), ('DCP', '决策评审点 (DCP)'), ('TR', '技术评审 (TR)')], max_length=20, verbose_name='阶段')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='评审标题')),
                ('decision', models.CharField(choices=[('PENDING', '待决策'), ('GO', '通过 (Go)'), ('KILL', '终止 (Kill)'), ('REDIRECT', '调整方向 (Redirect)')], default='PENDING', max_length=20, verbose_name='决策结果')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='决策日期')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='计划评审日期')),
                ('summary', models.TextField(blank=True, verbose_name='评审结论')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_gates', to='projects.project', verbose_name='项目')),
                ('reviewers', models.ManyToManyField(blank=True, related_name='stage_gate_reviews', to=settings.AUTH_USER_MODEL, verbose_name='评审人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'IPD阶段评审',
                'verbose_name_plural': 'IPD阶段评审',
                'db_table': 'plm_stage_gate',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'stage'], name='plm_stage_g_project_e92304_idx'), models.Index(fields=['decision'], name='plm_stage_g_decisio_592104_idx')],
            },
        ),
    ]
