# Generated by Django 5.2.16 on 2026-07-25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0017_projectbom_bom_type_stagegate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalreview',
            name='reviewers',
            field=models.ManyToManyField(
                related_name='proposal_reviews',
                through='projects.ProposalReviewItem',
                through_fields=('review', 'reviewer'),
                to=settings.AUTH_USER_MODEL,
                verbose_name='评审人',
            ),
        ),
    ]
