# Generated by Django 4.2.9

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='can_reject',
            field=models.BooleanField(default=True, verbose_name='允许拒绝'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='cc_roles',
            field=models.ManyToManyField(blank=True, related_name='workflow_step_cc', to='accounts.role', verbose_name='抄送角色'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='cc_users',
            field=models.ManyToManyField(blank=True, related_name='workflow_step_cc', to=settings.AUTH_USER_MODEL, verbose_name='抄送人'),
        ),
    ]

