# Generated by Django 4.2.9 on 2026-01-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_add_cc_can_reject'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflowinstance',
            new_name='workflow_in_busines_f6512a_idx',
            old_name='workflow_in_busines_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowinstance',
            new_name='workflow_in_status_e54cd6_idx',
            old_name='workflow_in_status_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowtask',
            new_name='workflow_ta_assigne_0a0571_idx',
            old_name='workflow_ta_assigne_g7h8i9_idx',
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='business_type',
            field=models.CharField(choices=[('PURCHASE_REQUEST', '采购申请'), ('EXPENSE', '费用报销'), ('SALES_ORDER', '销售订单'), ('PROJECT', '项目立项'), ('STOCK_ADJUSTMENT', '库存调整'), ('DELIVERY_ORDER', '发货单'), ('ECN', '工程变更')], max_length=30, verbose_name='业务类型'),
        ),
    ]
