# Generated by Django 4.2.9 on 2026-06-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_rename_workflow_in_busines_a1b2c3_idx_workflow_in_busines_f6512a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowdefinition',
            name='business_type',
            field=models.CharField(choices=[('PURCHASE_REQUEST', '采购申请'), ('PURCHASE_ORDER', '采购订单'), ('PURCHASE_CONTRACT', '采购合同'), ('OUTSOURCE_MATERIAL_ISSUE', '外协发料'), ('OUTSOURCE_RECEIPT', '外协收货'), ('CONTRACT_EXECUTION', '合同执行'), ('PAYMENT_RECORD', '合同付款'), ('QUOTATION', '销售报价'), ('SALES_ORDER', '销售订单'), ('SALES_CONTRACT', '销售合同'), ('DELIVERY_ORDER', '发货单'), ('SERVICE_REQUEST', '售后服务'), ('EXPENSE', '费用报销'), ('PAYMENT', '付款申请'), ('PROJECT', '项目立项'), ('ECN', '工程变更'), ('STOCK_ADJUSTMENT', '库存调整'), ('LEAVE_REQUEST', '请假申请'), ('OVERTIME_REQUEST', '加班申请'), ('VEHICLE_REQUEST', '用车申请'), ('ASSET_BORROW', '资产借用')], max_length=30, verbose_name='业务类型'),
        ),
    ]
