# Generated by Django 4.2.9 on 2026-07-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_workflowdefinition_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='action_type',
            field=models.CharField(choices=[('APPROVE', '审批'), ('REVIEW', '审核'), ('COUNTERSIGN', '会签'), ('OR_SIGN', '或签')], default='APPROVE', max_length=20, verbose_name='操作类型'),
        ),
    ]
