# Generated by Django 4.2.9 on 2026-07-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_alter_workflowstep_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtask',
            name='status',
            field=models.CharField(choices=[('PENDING', '待处理'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝'), ('RETURNED', '已退回'), ('SKIPPED', '已跳过'), ('TIMEOUT', '已超时')], default='PENDING', max_length=20, verbose_name='状态'),
        ),
    ]
