# Generated by Django 5.2.16 on 2026-07-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_unique_published_definition_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='timeout_action',
            field=models.CharField(choices=[('NONE', '仅提醒'), ('ESCALATE', '超时升级给上级')], default='NONE', help_text='ESCALATE：超时后把任务改派给原审批人的上级部门经理，原任务标记为已超时', max_length=20, verbose_name='超时处理方式'),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='event_type',
            field=models.CharField(choices=[('STARTED', '已发起'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('RETURNED', '已退回'), ('WITHDRAWN', '已撤回'), ('CANCELLED', '已取消'), ('TIMEOUT', '已超时改派')], max_length=20, verbose_name='事件类型'),
        ),
    ]
