# Generated by Django 5.2.16 on 2026-09-08 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='CodeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('prefix', models.CharField(max_length=10)),
                ('counter', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'lean_code_rule',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='我的公司', max_length=150)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'lean_company',
            },
        ),
        migrations.CreateModel(
            name='SchemaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'lean_schema',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=80)),
                ('resource', models.CharField(max_length=100)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lean_audit',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ActionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('operation', models.CharField(max_length=80)),
                ('fingerprint', models.CharField(max_length=64)),
                ('result', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lean_action_receipt',
                'constraints': [models.UniqueConstraint(fields=('actor', 'key'), name='lean_unique_action')],
            },
        ),
    ]
