# Generated by Django 4.2.9 on 2025-11-25 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_model', models.CharField(db_index=True, max_length=100, verbose_name='关联模型')),
                ('related_id', models.IntegerField(db_index=True, verbose_name='关联ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='文件类型')),
                ('category', models.CharField(choices=[('CONTRACT', '合同文件'), ('INVOICE', '发票'), ('RECEIPT', '收据'), ('CERTIFICATE', '证书/资质'), ('REPORT', '报告'), ('IMAGE', '图片'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='分类')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'db_table': 'attachment',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['related_model', 'related_id'], name='attachment_related_22382e_idx')],
            },
        ),
    ]
