# Generated by Django 5.2.16 on 2026-09-09 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_code_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('target', models.CharField(max_length=40)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('mode', models.CharField(max_length=10)),
                ('platform', models.CharField(max_length=10)),
                ('asset', models.JSONField(default=dict)),
                ('claim', models.CharField(blank=True, max_length=64)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('backup', models.CharField(blank=True, max_length=500)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'lean_upgrade_job',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
