# Generated by Django 4.2.9 on 2026-01-10 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_user_dingtalk_id_user_wechat_work_id'),
        ('core', '0004_add_code_rule_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('module', models.CharField(choices=[('sales', '销售管理'), ('purchase', '采购管理'), ('projects', '项目管理'), ('inventory', '库存管理'), ('finance', '财务管理'), ('masterdata', '基础数据'), ('accounts', '用户管理')], max_length=50, verbose_name='模块')),
                ('field_path', models.CharField(help_text='字段路径，支持关联查询如: project__manager', max_length=200, verbose_name='字段路径')),
                ('rule_type', models.CharField(choices=[('user', '关联用户'), ('department', '关联部门'), ('value', '固定值')], default='user', max_length=20, verbose_name='规则类型')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='规则描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '模块权限规则',
                'verbose_name_plural': '模块权限规则',
                'db_table': 'module_permission_rule',
                'ordering': ['module', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('module', models.CharField(choices=[('sales', '销售管理'), ('purchase', '采购管理'), ('projects', '项目管理'), ('inventory', '库存管理'), ('finance', '财务管理'), ('masterdata', '基础数据'), ('accounts', '用户管理')], max_length=50, verbose_name='模块')),
                ('permission_type', models.CharField(choices=[('all', '全部数据'), ('view_all', '只读全部'), ('department', '部门数据'), ('self', '仅本人'), ('rules', '按规则')], default='rules', max_length=20, verbose_name='权限类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '角色模块权限',
                'verbose_name_plural': '角色模块权限',
                'db_table': 'role_module_permission',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=200, verbose_name='公司名称')),
                ('company_short_name', models.CharField(blank=True, max_length=50, verbose_name='公司简称')),
                ('company_tax_no', models.CharField(blank=True, max_length=50, verbose_name='税号')),
                ('company_address', models.CharField(blank=True, max_length=300, verbose_name='公司地址')),
                ('company_phone', models.CharField(blank=True, max_length=50, verbose_name='公司电话')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='公司邮箱')),
                ('company_website', models.URLField(blank=True, verbose_name='公司网站')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='公司Logo')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='开户银行')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='银行账号')),
                ('legal_representative', models.CharField(blank=True, max_length=50, verbose_name='法人代表')),
                ('registered_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='注册资本')),
                ('default_currency', models.CharField(default='CNY', max_length=10, verbose_name='默认货币')),
                ('fiscal_year_start', models.IntegerField(default=1, verbose_name='财年起始月份')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system_config',
            },
        ),
        migrations.RenameIndex(
            model_name='codehistory',
            new_name='code_histor_rule_id_769e28_idx',
            old_name='code_histor_rule_id_b7e8a5_idx',
        ),
        migrations.RenameIndex(
            model_name='codehistory',
            new_name='code_histor_generat_852076_idx',
            old_name='code_histor_generat_0a3d4e_idx',
        ),
        migrations.RenameIndex(
            model_name='loginlog',
            new_name='login_log_usernam_1c12ba_idx',
            old_name='login_log_usernam_idx',
        ),
        migrations.RenameIndex(
            model_name='loginlog',
            new_name='login_log_ip_addr_c112fe_idx',
            old_name='login_log_ip_addr_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='webhook_del_status_41abe6_idx',
            old_name='webhook_del_status_idx',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='category',
            field=models.CharField(choices=[('CONTRACT', '合同文件'), ('INVOICE', '发票'), ('RECEIPT', '收据'), ('CERTIFICATE', '证书/资质'), ('REPORT', '报告'), ('IMAGE', '图片'), ('VIDEO', '视频'), ('FAULT_IMAGE', '故障图片'), ('FAULT_VIDEO', '故障视频'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='coderule',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
        migrations.AlterField(
            model_name='coderule',
            name='rule_type',
            field=models.CharField(choices=[('PROJECT', '项目编号'), ('ITEM', '物料编码'), ('PURCHASE_CONTRACT', '采购合同'), ('SALES_CONTRACT', '销售合同'), ('PURCHASE_REQUEST', '采购申请'), ('PURCHASE_ORDER', '采购订单'), ('SALES_ORDER', '销售订单'), ('SALES_QUOTE', '销售报价'), ('DELIVERY_ORDER', '发货单'), ('INVOICE', '发票'), ('GOODS_RECEIPT', '收货单'), ('STOCK_MOVE', '库存移动'), ('STOCK_ADJUSTMENT', '库存调整'), ('BUG', 'Bug编号'), ('PRODUCTION_PLAN', '生产计划'), ('DEBUG_RECORD', '调试记录'), ('QUALITY_INSPECTION', '质量检验')], max_length=50, unique=True, verbose_name='规则类型'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='rolemodulepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='accounts.role', verbose_name='角色'),
        ),
        migrations.AlterUniqueTogether(
            name='modulepermissionrule',
            unique_together={('module', 'field_path')},
        ),
        migrations.AlterUniqueTogether(
            name='rolemodulepermission',
            unique_together={('role', 'module')},
        ),
    ]
