# Generated by Django 4.2.9 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_permission_tree_model'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['code'], name='core_perm_code_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['type', 'is_active'], name='core_perm_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['parent', 'sort_order'], name='core_perm_parent_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['resource'], name='core_perm_resource_idx'),
        ),
    ]
