# Generated by Django 4.2.9 on 2026-03-11 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_overtimerequest_leaverequest_attendanceconfig_and_more'),
        ('core', '0008_add_permission_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.permission', verbose_name='权限')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色权限',
                'verbose_name_plural': '角色权限',
                'db_table': 'core_role_permission',
                'indexes': [models.Index(fields=['role'], name='core_roleperm_role_idx'), models.Index(fields=['permission'], name='core_roleperm_perm_idx')],
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='DataScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text='如 projects, sales, purchase', max_length=50, verbose_name='模块')),
                ('scope_type', models.CharField(choices=[('global', '全局数据'), ('department', '本部门数据'), ('department_and_below', '本部门及下级部门数据'), ('self', '仅本人数据'), ('custom', '自定义部门数据')], max_length=30, verbose_name='范围类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('departments', models.ManyToManyField(blank=True, help_text='仅当 scope_type 为 custom 时使用', related_name='data_scopes', to='accounts.department', verbose_name='自定义部门')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_scopes', to='accounts.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '数据权限范围',
                'verbose_name_plural': '数据权限范围',
                'db_table': 'core_data_scope',
                'indexes': [models.Index(fields=['role', 'module'], name='core_datascope_role_mod_idx'), models.Index(fields=['scope_type'], name='core_datascope_type_idx')],
                'unique_together': {('role', 'module')},
            },
        ),
    ]
