# Generated by Django 4.2.9 on 2026-03-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_overtimerequest_leaverequest_attendanceconfig_and_more'),
        ('core', '0009_add_role_permission_data_scope'),
    ]

    operations = [
        # Rename the M2M field from departments to custom_departments
        migrations.RenameField(
            model_name='datascope',
            old_name='departments',
            new_name='custom_departments',
        ),
        # Update scope_type choices
        migrations.AlterField(
            model_name='datascope',
            name='scope_type',
            field=models.CharField(
                choices=[
                    ('all', '全局数据'),
                    ('dept', '本部门数据'),
                    ('dept_tree', '本部门及下级部门数据'),
                    ('self', '仅本人数据'),
                    ('custom', '自定义部门数据')
                ],
                max_length=30,
                verbose_name='范围类型'
            ),
        ),
    ]
