# Generated by Django 4.2.9 on 2026-05-29 07:19
#
# fresh-replay 修复：上一迁移 0013_remove_old_permission_tables 已用
# RunSQL("DROP TABLE IF EXISTS ... CASCADE") 在 DB 层删除了 module_permission_rule /
# role_module_permission 两张表，但未同步 Django 迁移状态。原本自动生成的 DeleteModel 会再次
# 生成不带 IF EXISTS 的 DROP TABLE，导致从零重建数据库时报 "table ... does not exist"。
# 这里改用 SeparateDatabaseAndState：DB 层留空（删表已由 0013 完成），仅在「状态层」移除模型。
# 已应用该迁移的环境（生产/容器）按迁移名记录、不会重跑，不受影响；全新数据库可正确重放。

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_old_permission_tables'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='ModulePermissionRule',
                ),
                migrations.DeleteModel(
                    name='RoleModulePermission',
                ),
            ],
            database_operations=[],
        ),
    ]
