# Generated by Django 4.2.9 on 2026-06-01 08:04
#
# 生产兼容 / fresh-replay 修复：core IM 模型(Conversation/ConversationMember/Message/MessageRead，
# db_table 为 im_*，由 core 0006 创建)在生产库实际已不存在（0006 虽记为已应用，但这些 im_* 表
# 已不在库中）。原自动生成的 AlterUniqueTogether/DeleteModel 会在生产 migrate 时因「找不到约束/表」
# 抛 ValueError/ProgrammingError，导致部署中断。改用 SeparateDatabaseAndState：
#   - 状态层：照常移除字段与模型（纯状态操作，不触库、不做约束内省 → 不会报错）；
#   - DB 层：DROP TABLE IF EXISTS ... CASCADE 幂等删除（生产无表=no-op；全新库有表=正常删除）。
# 最终状态与原迁移一致（IM 模型全部移除），makemigrations --check 仍零漂移。

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_modulepermissionrule_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(name='conversationmember', unique_together=None),
                migrations.RemoveField(model_name='conversationmember', name='conversation'),
                migrations.RemoveField(model_name='conversationmember', name='created_by'),
                migrations.RemoveField(model_name='conversationmember', name='last_read_message'),
                migrations.RemoveField(model_name='conversationmember', name='updated_by'),
                migrations.RemoveField(model_name='conversationmember', name='user'),
                migrations.RemoveField(model_name='message', name='conversation'),
                migrations.RemoveField(model_name='message', name='created_by'),
                migrations.RemoveField(model_name='message', name='mentions'),
                migrations.RemoveField(model_name='message', name='reply_to'),
                migrations.RemoveField(model_name='message', name='sender'),
                migrations.RemoveField(model_name='message', name='updated_by'),
                migrations.AlterUniqueTogether(name='messageread', unique_together=None),
                migrations.RemoveField(model_name='messageread', name='created_by'),
                migrations.RemoveField(model_name='messageread', name='message'),
                migrations.RemoveField(model_name='messageread', name='updated_by'),
                migrations.RemoveField(model_name='messageread', name='user'),
                migrations.DeleteModel(name='Conversation'),
                migrations.DeleteModel(name='ConversationMember'),
                migrations.DeleteModel(name='Message'),
                migrations.DeleteModel(name='MessageRead'),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'DROP TABLE IF EXISTS im_message_read, im_message_mentions, im_message, '
                        'im_conversation_member, im_conversation CASCADE;'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
