# Generated by Django 4.2.9 on 2026-06-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_modulepermissionrule_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversationmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='conversationmember',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversationmember',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='conversationmember',
            name='last_read_message',
        ),
        migrations.RemoveField(
            model_name='conversationmember',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='conversationmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='mentions',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='messageread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='messageread',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='messageread',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messageread',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='messageread',
            name='user',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='ConversationMember',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageRead',
        ),
    ]
