# Generated by Django 4.2.9 on 2026-06-18 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_delete_im_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('action', models.CharField(choices=[('upgrade', '升级'), ('rollback', '回滚')], max_length=16, verbose_name='动作')),
                ('mode', models.CharField(choices=[('docker', 'Docker'), ('native', '原生')], max_length=16, verbose_name='部署模式')),
                ('from_version', models.CharField(max_length=32, verbose_name='升级前版本')),
                ('target_version', models.CharField(max_length=32, verbose_name='目标版本')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '执行中'), ('healthcheck', '健康检查'), ('success', '成功'), ('failed', '失败'), ('rolled_back', '已回滚')], default='pending', max_length=16, verbose_name='状态')),
                ('steps', models.JSONField(blank=True, default=list, verbose_name='步骤日志')),
                ('db_backup_path', models.CharField(blank=True, default='', max_length=512, verbose_name='DB 备份路径')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrade_jobs', to=settings.AUTH_USER_MODEL, verbose_name='触发人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '升级任务',
                'verbose_name_plural': '升级任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
