# Generated by Django 4.2.9 on 2026-07-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_upgradejob'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['user', 'is_read'], name='system_noti_user_id_843533_idx'),
        ),
    ]
