# Generated by Django 5.2.16 on 2026-07-25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0018_organization_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(
                related_name='meetings',
                through='core.MeetingParticipant',
                through_fields=('meeting', 'user'),
                to=settings.AUTH_USER_MODEL,
                verbose_name='参会人员',
            ),
        ),
    ]
