# Generated by Django 5.2.16 on 2026-07-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_meeting_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdelivery',
            name='status',
            field=models.CharField(choices=[('PENDING', '待发送'), ('SENDING', '发送中'), ('SUCCESS', '成功'), ('FAILED', '失败'), ('RETRYING', '重试中')], default='PENDING', max_length=20, verbose_name='状态'),
        ),
    ]
