# Generated by Django 4.2.9 on 2026-01-10 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IMConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='会话名称')),
                ('type', models.CharField(choices=[('PRIVATE', '私聊'), ('GROUP', '群聊')], default='PRIVATE', max_length=20, verbose_name='会话类型')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='im/avatars/', verbose_name='群头像')),
                ('description', models.TextField(blank=True, verbose_name='群描述')),
                ('max_members', models.IntegerField(default=500, verbose_name='最大成员数')),
                ('is_muted', models.BooleanField(default=False, verbose_name='全员禁言')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='最后消息时间')),
                ('last_message_content', models.CharField(blank=True, max_length=200, verbose_name='最后消息内容')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_im_conversations', to=settings.AUTH_USER_MODEL, verbose_name='群主')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'IM会话',
                'verbose_name_plural': 'IM会话',
                'db_table': 'oa_im_conversation',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IMMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('message_type', models.CharField(choices=[('TEXT', '文本'), ('IMAGE', '图片'), ('FILE', '文件'), ('AUDIO', '语音'), ('VIDEO', '视频'), ('SYSTEM', '系统消息')], default='TEXT', max_length=20, verbose_name='消息类型')),
                ('content', models.TextField(blank=True, verbose_name='消息内容')),
                ('file', models.FileField(blank=True, null=True, upload_to='im/files/%Y/%m/', verbose_name='文件')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='文件MIME类型')),
                ('is_mention_all', models.BooleanField(default=False, verbose_name='@所有人')),
                ('is_recalled', models.BooleanField(default=False, verbose_name='已撤回')),
                ('recalled_at', models.DateTimeField(blank=True, null=True, verbose_name='撤回时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='oa.imconversation', verbose_name='会话')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='im_mentioned_in_messages', to=settings.AUTH_USER_MODEL, verbose_name='@提及的用户')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='oa.immessage', verbose_name='回复的消息')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='im_sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'IM消息',
                'verbose_name_plural': 'IM消息',
                'db_table': 'oa_im_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IMConversationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('role', models.CharField(choices=[('OWNER', '群主'), ('ADMIN', '管理员'), ('MEMBER', '成员')], default='MEMBER', max_length=20, verbose_name='角色')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='群昵称')),
                ('is_muted', models.BooleanField(default=False, verbose_name='消息免打扰')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='最后已读时间')),
                ('last_read_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='最后已读消息ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='oa.imconversation', verbose_name='会话')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL, verbose_name='邀请人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='im_conversation_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'IM会话成员',
                'verbose_name_plural': 'IM会话成员',
                'db_table': 'oa_im_conversation_member',
            },
        ),
        migrations.CreateModel(
            name='IMMessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='已读时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='oa.immessage', verbose_name='消息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='im_read_messages', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'IM消息已读记录',
                'verbose_name_plural': 'IM消息已读记录',
                'db_table': 'oa_im_message_read',
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='immessage',
            index=models.Index(fields=['conversation', 'created_at'], name='oa_im_messa_convers_e51aca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imconversationmember',
            unique_together={('conversation', 'user')},
        ),
    ]
