# Generated by Django 4.2.9 on 2026-06-01 08:04
#
# 生产兼容 / fresh-replay 修复：oa IM 模型(IMConversation/IMConversationMember/IMMessage/IMMessageRead，
# db_table 为 oa_im_*)在生产库的实际 schema 与迁移状态不一致（oa_im_conversation_member 缺 unique_together
# 约束、oa_im_message_read 表缺失）。原自动生成的 AlterUniqueTogether/DeleteModel 会在生产 migrate 时
# 因「找不到约束/表」抛 ValueError/ProgrammingError，导致部署中断。改用 SeparateDatabaseAndState：
#   - 状态层：照常移除字段与模型（纯状态操作，不触库、不做约束内省 → 不会报错）；
#   - DB 层：DROP TABLE IF EXISTS ... CASCADE 幂等删除（缺失的表=no-op；存在的表=正常删除）。
# 最终状态与原迁移一致（IM 模型全部移除），makemigrations --check 仍零漂移。

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0003_asset_attendancedevice_signaturedocument_vehicle_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(name='imconversationmember', unique_together=None),
                migrations.RemoveField(model_name='imconversationmember', name='conversation'),
                migrations.RemoveField(model_name='imconversationmember', name='created_by'),
                migrations.RemoveField(model_name='imconversationmember', name='invited_by'),
                migrations.RemoveField(model_name='imconversationmember', name='updated_by'),
                migrations.RemoveField(model_name='imconversationmember', name='user'),
                migrations.RemoveField(model_name='immessage', name='conversation'),
                migrations.RemoveField(model_name='immessage', name='created_by'),
                migrations.RemoveField(model_name='immessage', name='mentioned_users'),
                migrations.RemoveField(model_name='immessage', name='reply_to'),
                migrations.RemoveField(model_name='immessage', name='sender'),
                migrations.RemoveField(model_name='immessage', name='updated_by'),
                migrations.AlterUniqueTogether(name='immessageread', unique_together=None),
                migrations.RemoveField(model_name='immessageread', name='message'),
                migrations.RemoveField(model_name='immessageread', name='user'),
                migrations.DeleteModel(name='IMConversation'),
                migrations.DeleteModel(name='IMConversationMember'),
                migrations.DeleteModel(name='IMMessage'),
                migrations.DeleteModel(name='IMMessageRead'),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'DROP TABLE IF EXISTS oa_im_message_read, oa_im_message_mentioned_users, oa_im_message, '
                        'oa_im_conversation_member, oa_im_conversation CASCADE;'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
