# Generated by Django 4.2.9 on 2026-06-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0003_asset_attendancedevice_signaturedocument_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imconversationmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='imconversationmember',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='imconversationmember',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='imconversationmember',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='imconversationmember',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='imconversationmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='immessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='immessage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='immessage',
            name='mentioned_users',
        ),
        migrations.RemoveField(
            model_name='immessage',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='immessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='immessage',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='immessageread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='immessageread',
            name='message',
        ),
        migrations.RemoveField(
            model_name='immessageread',
            name='user',
        ),
        migrations.DeleteModel(
            name='IMConversation',
        ),
        migrations.DeleteModel(
            name='IMConversationMember',
        ),
        migrations.DeleteModel(
            name='IMMessage',
        ),
        migrations.DeleteModel(
            name='IMMessageRead',
        ),
    ]
