# Generated by Django 4.2.9 on 2026-01-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_remove_warehouse_location_warehouse_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='银行账号'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='开户银行'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='开票名称'),
        ),
        migrations.AddField(
            model_name='customer',
            name='registered_address',
            field=models.TextField(blank=True, verbose_name='注册地址'),
        ),
        migrations.AddField(
            model_name='customer',
            name='registered_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='注册电话'),
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='item',
            name='lead_time',
            field=models.IntegerField(default=0, verbose_name='采购周期(天)'),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, verbose_name='生产厂家'),
        ),
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='型号'),
        ),
        migrations.AddField(
            model_name='item',
            name='origin_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='产地'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='采购单价'),
        ),
        migrations.AddField(
            model_name='item',
            name='safety_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='安全库存'),
        ),
        migrations.AddField(
            model_name='item',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='销售单价'),
        ),
        migrations.AddField(
            model_name='item',
            name='shelf_life',
            field=models.IntegerField(default=0, verbose_name='保质期(天)'),
        ),
        migrations.AddField(
            model_name='item',
            name='tax_rate',
            field=models.IntegerField(choices=[(0, '0%'), (1, '1%'), (3, '3%'), (6, '6%'), (9, '9%'), (13, '13%')], default=13, verbose_name='税率(%)'),
        ),
        migrations.AddField(
            model_name='item',
            name='volume',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='体积(m³)'),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='重量(kg)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='invoice_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='开票名称'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='registered_address',
            field=models.TextField(blank=True, verbose_name='注册地址'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='registered_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='注册电话'),
        ),
    ]
