# Generated by Django 4.2.9 on 2026-07-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_supplier_settlement_method_alter_item_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A级'), ('B', 'B级'), ('C', 'C级'), ('D', 'D级'), ('E', 'E级')], default='', max_length=10, verbose_name='供应商等级'),
        ),
    ]
