# Generated by Django 4.2.9 on 2025-12-01 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_batch_batchmove_batch_batch_item_id_c6f35d_idx_and_more'),
        ('inventory', '0002_inventorylot_lotconsumption'),
    ]

    operations = [
    ]
