# Generated by Django 4.2.9 on 2026-01-10 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_bug_models'),
        ('masterdata', '0003_customer_bank_account_customer_bank_name_and_more'),
        ('inventory', '0003_merge_20251201_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('requisition_no', models.CharField(max_length=50, unique=True, verbose_name='领料单号')),
                ('requisition_type', models.CharField(choices=[('PROJECT', '项目领料'), ('AFTERSALES', '售后领料')], max_length=20, verbose_name='领料类型')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '待审批'), ('APPROVED', '已批准'), ('PENDING', '待备料'), ('PREPARING', '备料中'), ('READY', '备料完成'), ('ISSUED', '已出库'), ('PARTIAL', '部分出库'), ('REJECTED', '已拒绝'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('request_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='申请日期')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='需求日期')),
                ('issue_date', models.DateTimeField(blank=True, null=True, verbose_name='出库时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '领料单',
                'verbose_name_plural': '领料单',
                'db_table': 'material_requisition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequisitionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='申请数量')),
                ('issued_qty', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='已出库数量')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='单位成本')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '领料单明细',
                'verbose_name_plural': '领料单明细',
                'db_table': 'material_requisition_line',
            },
        ),
        migrations.CreateModel(
            name='MaterialReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('return_no', models.CharField(max_length=50, unique=True, verbose_name='退料单号')),
                ('return_type', models.CharField(choices=[('PROJECT', '项目退料'), ('AFTERSALES', '售后退料')], max_length=20, verbose_name='退料类型')),
                ('return_reason', models.CharField(choices=[('SURPLUS', '物料剩余'), ('REPLACEMENT', '物料更换'), ('SCRAP', '物料报废'), ('DEFECTIVE', '物料不良'), ('OTHER', '其他')], default='SURPLUS', max_length=20, verbose_name='退料原因')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待入库'), ('INSPECTING', '检验中'), ('COMPLETED', '已入库'), ('PARTIAL', '部分入库'), ('REJECTED', '已拒绝'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('request_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='申请日期')),
                ('receive_date', models.DateTimeField(blank=True, null=True, verbose_name='入库时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '退料单',
                'verbose_name_plural': '退料单',
                'db_table': 'material_return',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='退料数量')),
                ('received_qty', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='已入库数量')),
                ('condition', models.CharField(choices=[('GOOD', '良品'), ('DAMAGED', '损坏'), ('SCRAP', '报废')], default='GOOD', max_length=20, verbose_name='物料状态')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='单位成本')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '退料单明细',
                'verbose_name_plural': '退料单明细',
                'db_table': 'material_return_line',
            },
        ),
        migrations.RenameIndex(
            model_name='inventorylot',
            new_name='inventory_l_item_id_c64cd3_idx',
            old_name='inventory_l_item_id_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorylot',
            new_name='inventory_l_remaini_2ef31c_idx',
            old_name='inventory_l_remaini_def456_idx',
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '审批中'), ('APPROVED', '已审批'), ('REJECTED', '已拒绝'), ('CONFIRMED', '已确认')], default='DRAFT', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='materialreturnline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='materialreturnline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='masterdata.item', verbose_name='物料'),
        ),
        migrations.AddField(
            model_name='materialreturnline',
            name='material_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.materialreturn', verbose_name='退料单'),
        ),
        migrations.AddField(
            model_name='materialreturnline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='aftersales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_returns', to='projects.aftersalesorder', verbose_name='售后工单'),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_returns', to='projects.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_returns', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_returns', to='masterdata.warehouse', verbose_name='入库仓库'),
        ),
        migrations.AddField(
            model_name='materialreturn',
            name='warehouse_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_returns', to=settings.AUTH_USER_MODEL, verbose_name='仓库操作员'),
        ),
        migrations.AddField(
            model_name='materialrequisitionline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='materialrequisitionline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisition_lines', to='masterdata.item', verbose_name='物料'),
        ),
        migrations.AddField(
            model_name='materialrequisitionline',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.materialrequisition', verbose_name='领料单'),
        ),
        migrations.AddField(
            model_name='materialrequisitionline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='aftersales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_requisitions', to='projects.aftersalesorder', verbose_name='售后工单'),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_requisitions', to='projects.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requisitions', to='masterdata.warehouse', verbose_name='出库仓库'),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='warehouse_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='仓库操作员'),
        ),
    ]
