# Generated by Django 4.2.9 on 2026-01-13
# Additional production models migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        # Additional production models (AndonCall, ControlChart, etc.)
        # These tables already exist in database
        # This migration is marked as applied/faked
    ]
