# Generated by Django 4.2.9 on 2025-11-23 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='仓库编码')),
                ('name', models.CharField(max_length=200, verbose_name='仓库名称')),
                ('warehouse_type', models.CharField(choices=[('MAIN', '主仓库'), ('BRANCH', '分仓库'), ('TRANSIT', '中转仓'), ('VIRTUAL', '虚拟仓')], default='MAIN', max_length=20, verbose_name='仓库类型')),
                ('location', models.TextField(blank=True, verbose_name='地址')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='仓库管理员')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'db_table': 'warehouse',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='供应商编码')),
                ('name', models.CharField(max_length=200, verbose_name='供应商名称')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='简称')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('payment_terms', models.CharField(blank=True, max_length=100, verbose_name='付款条款')),
                ('tax_number', models.CharField(blank=True, max_length=100, verbose_name='税号')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='开户银行')),
                ('bank_account', models.CharField(blank=True, max_length=100, verbose_name='银行账号')),
                ('status', models.CharField(choices=[('ACTIVE', '激活'), ('INACTIVE', '停用'), ('POTENTIAL', '潜在供应商')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'supplier',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=100, verbose_name='类别名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='类别编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='masterdata.itemcategory', verbose_name='上级类别')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '物料类别',
                'verbose_name_plural': '物料类别',
                'db_table': 'item_category',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU编码')),
                ('name', models.CharField(max_length=200, verbose_name='物料名称')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格型号')),
                ('item_type', models.CharField(choices=[('MATERIAL', '原材料'), ('PRODUCT', '产成品'), ('SEMI', '半成品'), ('SERVICE', '服务')], default='MATERIAL', max_length=20, verbose_name='物料类型')),
                ('unit', models.CharField(choices=[('PCS', '个'), ('KG', '千克'), ('M', '米'), ('M2', '平方米'), ('M3', '立方米'), ('SET', '套'), ('BOX', '箱'), ('PACK', '包'), ('HOUR', '小时')], default='PCS', max_length=20, verbose_name='单位')),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='标准成本')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='最小库存')),
                ('max_stock', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='最大库存')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image', models.ImageField(blank=True, upload_to='items/', verbose_name='图片')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='条形码')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='masterdata.itemcategory', verbose_name='物料类别')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('default_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_items', to='masterdata.supplier', verbose_name='默认供应商')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料',
                'db_table': 'item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='客户编码')),
                ('name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='简称')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='信用额度')),
                ('payment_terms', models.CharField(blank=True, max_length=100, verbose_name='付款条款')),
                ('tax_number', models.CharField(blank=True, max_length=100, verbose_name='税号')),
                ('status', models.CharField(choices=[('ACTIVE', '激活'), ('INACTIVE', '停用'), ('POTENTIAL', '潜在客户')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customer',
                'ordering': ['-created_at'],
            },
        ),
    ]
