# Generated by Django 4.2.9 on 2025-11-25 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='location',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.TextField(blank=True, verbose_name='地址'),
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=50, verbose_name='库位编码')),
                ('name', models.CharField(max_length=100, verbose_name='库位名称')),
                ('location_type', models.CharField(choices=[('ZONE', '区域'), ('AISLE', '通道'), ('RACK', '货架'), ('SHELF', '层'), ('BIN', '库位')], default='BIN', max_length=20, verbose_name='库位类型')),
                ('full_path', models.CharField(blank=True, max_length=200, verbose_name='完整路径')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最大承重(kg)')),
                ('max_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最大容积(m³)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('is_pickable', models.BooleanField(default=True, verbose_name='可拣货')),
                ('is_storable', models.BooleanField(default=True, verbose_name='可存储')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='masterdata.warehouselocation', verbose_name='上级库位')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='masterdata.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库位',
                'verbose_name_plural': '库位',
                'db_table': 'warehouse_location',
                'ordering': ['warehouse', 'sort_order', 'code'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
    ]
