# Generated by Django 4.2.9 on 2026-01-13 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_creditlevel_customerreminder_customerfollowup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='abc_class',
            field=models.CharField(choices=[('A', 'A类-高价值'), ('B', 'B类-中价值'), ('C', 'C类-低价值')], default='C', max_length=1, verbose_name='ABC分类'),
        ),
        migrations.AddField(
            model_name='item',
            name='alternate_items',
            field=models.ManyToManyField(blank=True, related_name='alternate_for', to='masterdata.item', verbose_name='可替代物料'),
        ),
        migrations.AddField(
            model_name='item',
            name='can_substitute',
            field=models.BooleanField(default=False, verbose_name='允许替代'),
        ),
        migrations.AddField(
            model_name='item',
            name='default_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='默认库位'),
        ),
        migrations.AddField(
            model_name='item',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_items', to='masterdata.warehouse', verbose_name='默认仓库'),
        ),
        migrations.AddField(
            model_name='item',
            name='diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='直径(mm)'),
        ),
        migrations.AddField(
            model_name='item',
            name='drawing_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='图纸号'),
        ),
        migrations.AddField(
            model_name='item',
            name='drawing_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='图纸版本'),
        ),
        migrations.AddField(
            model_name='item',
            name='economic_order_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='经济订货批量'),
        ),
        migrations.AddField(
            model_name='item',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, help_text='用户自定义的扩展字段', verbose_name='扩展字段'),
        ),
        migrations.AddField(
            model_name='item',
            name='heat_treatment',
            field=models.CharField(blank=True, help_text='如：调质HRC28-32、渗碳淬火等', max_length=100, verbose_name='热处理'),
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='高度(mm)'),
        ),
        migrations.AddField(
            model_name='item',
            name='inspection_standard',
            field=models.TextField(blank=True, verbose_name='检验标准'),
        ),
        migrations.AddField(
            model_name='item',
            name='inspection_type',
            field=models.CharField(choices=[('NONE', '免检'), ('INCOMING', '来料检验'), ('SAMPLE', '抽检'), ('FULL', '全检')], default='INCOMING', max_length=20, verbose_name='检验方式'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='影响产品关键性能或交期的核心部件', verbose_name='关键件'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_long_lead',
            field=models.BooleanField(default=False, help_text='采购周期超过项目标准周期', verbose_name='长周期件'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_property',
            field=models.CharField(choices=[('STANDARD', '标准件'), ('PURCHASED', '外购件'), ('OUTSOURCED', '外协件'), ('SELF_MADE', '自制件'), ('CONSUMABLE', '易耗品'), ('VIRTUAL', '虚拟件'), ('ASSEMBLY', '组件')], default='PURCHASED', help_text='标准件/外购件/外协件/自制件等', max_length=20, verbose_name='物料属性'),
        ),
        migrations.AddField(
            model_name='item',
            name='last_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='最近采购价'),
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='长度(mm)'),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, help_text='如：45#钢、SUS304、6061铝合金等', max_length=100, verbose_name='材质'),
        ),
        migrations.AddField(
            model_name='item',
            name='qr_code',
            field=models.CharField(blank=True, max_length=200, verbose_name='二维码'),
        ),
        migrations.AddField(
            model_name='item',
            name='reorder_point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='再订货点'),
        ),
        migrations.AddField(
            model_name='item',
            name='surface_treatment',
            field=models.CharField(blank=True, help_text='如：镀锌、发黑、阳极氧化、喷涂等', max_length=100, verbose_name='表面处理'),
        ),
        migrations.AddField(
            model_name='item',
            name='technical_params',
            field=models.JSONField(blank=True, default=dict, help_text='如：{"电压":"24V", "功率":"100W", "精度":"0.01mm"}', verbose_name='技术参数'),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='宽度(mm)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('PCS', '个'), ('KG', '千克'), ('G', '克'), ('M', '米'), ('MM', '毫米'), ('M2', '平方米'), ('M3', '立方米'), ('SET', '套'), ('BOX', '箱'), ('PACK', '包'), ('HOUR', '小时'), ('L', '升'), ('ML', '毫升'), ('ROLL', '卷'), ('PAIR', '对')], default='PCS', max_length=20, verbose_name='单位'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_property'], name='item_item_pr_ca2bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['abc_class'], name='item_abc_cla_e86b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_critical'], name='item_is_crit_4770b0_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['drawing_no'], name='item_drawing_e73ba2_idx'),
        ),
    ]
