# Generated by Django 4.2.9 on 2026-03-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_automation_bom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='settlement_method',
            field=models.CharField(blank=True, choices=[('PREPAY', '预付款'), ('COD', '货到付款'), ('NET15', '月结15天'), ('NET30', '月结30天'), ('NET45', '月结45天'), ('NET60', '月结60天'), ('NET90', '月结90天'), ('NET120', '月结120天'), ('ACCEPTANCE', '承兑汇票'), ('OTHER', '其他')], max_length=20, verbose_name='结款方式'),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, help_text='可选，用于仓库扫码', max_length=100, verbose_name='条形码'),
        ),
        migrations.AlterField(
            model_name='item',
            name='qr_code',
            field=models.CharField(blank=True, help_text='可选，用于仓库扫码', max_length=200, verbose_name='二维码'),
        ),
    ]
