# Generated by Django 4.2.9 on 2025-11-23 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('purchase', '0001_initial'),
        ('projects', '0001_initial'),
        ('masterdata', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('expense_no', models.CharField(max_length=50, unique=True, verbose_name='报销单号')),
                ('expense_date', models.DateField(verbose_name='费用日期')),
                ('category', models.CharField(choices=[('TRAVEL', '差旅费'), ('ENTERTAINMENT', '招待费'), ('OFFICE', '办公费'), ('TRANSPORTATION', '交通费'), ('COMMUNICATION', '通讯费'), ('TRAINING', '培训费'), ('OTHER', '其他')], max_length=20, verbose_name='费用类别')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='金额')),
                ('description', models.TextField(verbose_name='费用说明')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('REIMBURSED', '已报销')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('reimbursement_date', models.DateField(blank=True, null=True, verbose_name='报销日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounts.department', verbose_name='关联部门')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='projects.project', verbose_name='关联项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='报销人')),
            ],
            options={
                'verbose_name': '费用报销',
                'verbose_name_plural': '费用报销',
                'db_table': 'expense',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('ar_no', models.CharField(max_length=50, unique=True, verbose_name='应收单号')),
                ('invoice_no', models.CharField(blank=True, max_length=100, verbose_name='发票号')),
                ('invoice_date', models.DateField(verbose_name='开票日期')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='应收金额')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='已收金额')),
                ('due_date', models.DateField(verbose_name='到期日期')),
                ('status', models.CharField(choices=[('PENDING', '待收款'), ('PARTIAL', '部分收款'), ('PAID', '已收款'), ('OVERDUE', '逾期'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='masterdata.customer', verbose_name='客户')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='projects.project', verbose_name='关联项目')),
                ('so', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to='sales.salesorder', verbose_name='销售订单')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '应收账款',
                'verbose_name_plural': '应收账款',
                'db_table': 'account_receivable',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('ap_no', models.CharField(max_length=50, unique=True, verbose_name='应付单号')),
                ('invoice_no', models.CharField(blank=True, max_length=100, verbose_name='发票号')),
                ('invoice_date', models.DateField(verbose_name='开票日期')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='应付金额')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='已付金额')),
                ('due_date', models.DateField(verbose_name='到期日期')),
                ('status', models.CharField(choices=[('PENDING', '待付款'), ('PARTIAL', '部分付款'), ('PAID', '已付款'), ('OVERDUE', '逾期'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='purchase.purchaseorder', verbose_name='采购订单')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='masterdata.supplier', verbose_name='供应商')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '应付账款',
                'verbose_name_plural': '应付账款',
                'db_table': 'account_payable',
                'ordering': ['-created_at'],
            },
        ),
    ]
