# Generated by Django 4.2.9 on 2025-11-26 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_sharedexpense_sharedexpenseallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('invoice_type', models.CharField(choices=[('INPUT', '进项发票'), ('OUTPUT', '销项发票')], max_length=10, verbose_name='发票类型')),
                ('invoice_no', models.CharField(max_length=50, unique=True, verbose_name='发票号')),
                ('invoice_date', models.DateField(verbose_name='开票日期')),
                ('party_name', models.CharField(max_length=200, verbose_name='对方单位')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='税号')),
                ('amount_before_tax', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='金额（不含税）')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='税额')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='价税合计')),
                ('reference_type', models.CharField(blank=True, choices=[('SALES_ORDER', '销售订单'), ('PURCHASE_ORDER', '采购订单'), ('EXPENSE', '费用报销')], max_length=20, null=True, verbose_name='关联单据类型')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='关联单据ID')),
                ('status', models.CharField(choices=[('REGISTERED', '已登记'), ('CERTIFIED', '已认证'), ('VOID', '已作废')], default='REGISTERED', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '发票',
                'verbose_name_plural': '发票',
                'db_table': 'invoice',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
    ]
