# Generated by Django 4.2.9 on 2025-12-29 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_remove_warehouse_location_warehouse_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0005_bank_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('batch_no', models.CharField(max_length=50, unique=True, verbose_name='批次号')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('import_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='导入时间')),
                ('total_count', models.IntegerField(default=0, verbose_name='总记录数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功导入数')),
                ('error_count', models.IntegerField(default=0, verbose_name='错误数')),
                ('matched_count', models.IntegerField(default=0, verbose_name='自动匹配数')),
                ('debit_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='支出总额')),
                ('credit_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='收入总额')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('error_details', models.JSONField(default=list, verbose_name='错误详情')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '银行流水导入日志',
                'verbose_name_plural': '银行流水导入日志',
                'db_table': 'bank_statement_import_log',
                'ordering': ['-import_time'],
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('import_batch', models.CharField(db_index=True, max_length=50, verbose_name='导入批次号')),
                ('import_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='导入时间')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='源文件名')),
                ('voucher_no', models.CharField(blank=True, max_length=100, verbose_name='凭证号')),
                ('counterparty_account', models.CharField(blank=True, max_length=100, verbose_name='对方账号')),
                ('transaction_time', models.DateTimeField(verbose_name='交易时间')),
                ('transaction_type', models.CharField(choices=[('DEBIT', '借（支出）'), ('CREDIT', '贷（收入）')], max_length=10, verbose_name='借贷标志')),
                ('counterparty_name', models.CharField(max_length=255, verbose_name='对方单位')),
                ('counterparty_bank', models.CharField(blank=True, max_length=100, verbose_name='对方行号')),
                ('purpose', models.CharField(blank=True, max_length=100, verbose_name='用途')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='摘要')),
                ('postscript', models.TextField(blank=True, verbose_name='附言')),
                ('receipt_info', models.TextField(blank=True, verbose_name='回单个性化信息')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='转入金额')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='转出金额')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='余额')),
                ('payment_voucher_type', models.CharField(blank=True, max_length=50, verbose_name='支付凭证种类')),
                ('status', models.CharField(choices=[('PENDING', '待匹配'), ('MATCHED', '已匹配'), ('IGNORED', '已忽略'), ('ERROR', '匹配错误')], default='PENDING', max_length=20, verbose_name='状态')),
                ('match_type', models.CharField(blank=True, choices=[('AP', '应付账款'), ('AR', '应收账款'), ('EXPENSE', '费用'), ('OTHER', '其他')], max_length=20, null=True, verbose_name='匹配类型')),
                ('match_confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='匹配置信度(%)')),
                ('match_notes', models.TextField(blank=True, verbose_name='匹配备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statements', to='masterdata.customer', verbose_name='匹配客户')),
                ('related_ap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statements', to='finance.accountpayable', verbose_name='关联应付账款')),
                ('related_ar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statements', to='finance.accountreceivable', verbose_name='关联应收账款')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statements', to='finance.payment', verbose_name='关联付款记录')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statements', to='masterdata.supplier', verbose_name='匹配供应商')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '银行流水',
                'verbose_name_plural': '银行流水',
                'db_table': 'bank_statement',
                'ordering': ['-transaction_time'],
                'indexes': [models.Index(fields=['counterparty_name'], name='bank_statem_counter_ecd1ce_idx'), models.Index(fields=['transaction_time'], name='bank_statem_transac_8fe74c_idx'), models.Index(fields=['status'], name='bank_statem_status_14bb39_idx'), models.Index(fields=['import_batch'], name='bank_statem_import__8a6620_idx')],
            },
        ),
    ]
