# Generated by Django 4.2.9 on 2025-12-29 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0006_bank_statement_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('line_no', models.IntegerField(default=1, verbose_name='行号')),
                ('tax_category_code', models.CharField(blank=True, max_length=50, verbose_name='税收分类编码')),
                ('business_type', models.CharField(blank=True, max_length=100, verbose_name='特定业务类型')),
                ('item_name', models.CharField(max_length=500, verbose_name='货物或应税劳务名称')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格型号')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='单位')),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='数量')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='单价')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='金额')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='税率(%)')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='税额')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice', verbose_name='发票')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '发票明细',
                'verbose_name_plural': '发票明细',
                'db_table': 'invoice_item',
                'ordering': ['invoice', 'line_no'],
            },
        ),
    ]

