# Generated by Django 4.2.9 on 2026-01-10 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_add_sales_contract'),
        ('projects', '0005_bug_models'),
        ('masterdata', '0003_customer_bank_account_customer_bank_name_and_more'),
        ('finance', '0011_fix_payment_schedule_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('milestone_type', models.CharField(choices=[('ADVANCE', '预付款'), ('DELIVERY', '发货款'), ('INSTALLATION', '安装款'), ('ACCEPTANCE', '验收款'), ('WARRANTY', '质保款'), ('FINAL', '尾款'), ('OTHER', '其他')], max_length=20, verbose_name='节点类型')),
                ('name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='占比%')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='计划金额')),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='已收金额')),
                ('planned_date', models.DateField(verbose_name='计划收款日期')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际收款日期')),
                ('trigger_condition', models.CharField(blank=True, max_length=200, verbose_name='触发条件')),
                ('is_triggered', models.BooleanField(default=False, verbose_name='条件已触发')),
                ('triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='触发时间')),
                ('status', models.CharField(choices=[('PENDING', '待收款'), ('PARTIAL', '部分收款'), ('COLLECTED', '已收款'), ('OVERDUE', '已逾期'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='状态')),
                ('reminder_days', models.IntegerField(default=7, verbose_name='提前提醒天数')),
                ('last_reminder', models.DateTimeField(blank=True, null=True, verbose_name='上次提醒时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '回款节点',
                'verbose_name_plural': '回款节点',
                'db_table': 'collection_milestone',
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='CollectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('plan_no', models.CharField(max_length=50, unique=True, verbose_name='计划编号')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='合同总金额')),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='计划回款金额')),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='已回款金额')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('CONFIRMED', '已确认'), ('IN_PROGRESS', '执行中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '回款计划',
                'verbose_name_plural': '回款计划',
                'db_table': 'collection_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('collection_date', models.DateField(verbose_name='收款日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='收款金额')),
                ('payment_method', models.CharField(choices=[('BANK', '银行转账'), ('CHECK', '支票'), ('CASH', '现金'), ('ACCEPTANCE', '承兑汇票'), ('OTHER', '其他')], default='BANK', max_length=20, verbose_name='付款方式')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='付款银行')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='付款账号')),
                ('transaction_no', models.CharField(blank=True, max_length=100, verbose_name='交易流水号')),
                ('confirmed', models.BooleanField(default=False, verbose_name='已确认')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '收款记录',
                'verbose_name_plural': '收款记录',
                'db_table': 'collection_record',
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='CollectionReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('reminder_type', models.CharField(choices=[('UPCOMING', '即将到期'), ('DUE', '到期提醒'), ('OVERDUE', '逾期提醒')], max_length=20, verbose_name='提醒类型')),
                ('reminder_date', models.DateTimeField(verbose_name='提醒时间')),
                ('sent', models.BooleanField(default=False, verbose_name='已发送')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('message', models.TextField(blank=True, verbose_name='提醒内容')),
            ],
            options={
                'verbose_name': '回款提醒',
                'verbose_name_plural': '回款提醒',
                'db_table': 'collection_reminder',
                'ordering': ['reminder_date'],
            },
        ),
        migrations.RenameIndex(
            model_name='paymentschedule',
            new_name='payment_sch_sales_o_f342b5_idx',
            old_name='payment_sch_sales_o_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentschedule',
            new_name='payment_sch_status_30598f_idx',
            old_name='payment_sch_status_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentschedule',
            new_name='payment_sch_reminde_4debde_idx',
            old_name='payment_sch_remind_idx',
        ),
        migrations.RenameIndex(
            model_name='purchasepaymentschedule',
            new_name='purchase_pa_purchas_dbc895_idx',
            old_name='pps_po_order_idx',
        ),
        migrations.RenameIndex(
            model_name='purchasepaymentschedule',
            new_name='purchase_pa_status_f07ed3_idx',
            old_name='pps_status_idx',
        ),
        migrations.RenameIndex(
            model_name='purchasepaymentschedule',
            new_name='purchase_pa_reminde_ca24cc_idx',
            old_name='pps_remind_idx',
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='购买方名称'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_tax_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='购方识别号'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='digital_invoice_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='数电发票号码'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_category',
            field=models.CharField(blank=True, choices=[('SPECIAL', '数电发票（增值税专用发票）'), ('NORMAL', '数电发票（普通发票）'), ('PAPER_SPECIAL', '纸质增值税专用发票'), ('PAPER_NORMAL', '纸质普通发票')], max_length=50, verbose_name='发票票种'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='发票代码'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='发票来源'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='销方名称'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_tax_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='销方识别号'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(verbose_name='开票日期'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('REGISTERED', '已登记'), ('CERTIFIED', '已认证'), ('VOID', '已作废'), ('NORMAL', '正常'), ('RED', '红冲')], default='REGISTERED', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
        migrations.AlterField(
            model_name='purchasepaymentschedule',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='collectionreminder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='collectionreminder',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='finance.collectionmilestone', verbose_name='回款节点'),
        ),
        migrations.AddField(
            model_name='collectionreminder',
            name='recipients',
            field=models.ManyToManyField(related_name='collection_reminders', to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
        ),
        migrations.AddField(
            model_name='collectionreminder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_collections', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_records', to='finance.invoice', verbose_name='关联发票'),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='finance.collectionmilestone', verbose_name='回款节点'),
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_plans', to='sales.salescontract', verbose_name='销售合同'),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_plans', to='masterdata.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_plans', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_plans', to='projects.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_plans', to='sales.salesorder', verbose_name='销售订单'),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='collectionmilestone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='collectionmilestone',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='finance.collectionplan', verbose_name='回款计划'),
        ),
        migrations.AddField(
            model_name='collectionmilestone',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
    ]
