# Generated by Django 4.2.9 on 2026-07-06 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_supplier_settlement_method_alter_item_barcode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0015_alter_drawing_project'),
        ('finance', '0016_taxdeclaration_bankstatement_bank_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('source_type', models.CharField(max_length=30, verbose_name='来源类型')),
                ('source_id', models.PositiveIntegerField(verbose_name='来源单据ID')),
                ('source_no', models.CharField(blank=True, default='', max_length=50, verbose_name='来源单号')),
                ('category', models.CharField(blank=True, default='', max_length=30, verbose_name='费用类别')),
                ('payee_name', models.CharField(blank=True, default='', max_length=255, verbose_name='收款方')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='应付金额')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='已付金额')),
                ('status', models.CharField(choices=[('PENDING', '待付'), ('PARTIAL', '部分'), ('PAID', '已付'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='状态')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='应付日期')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable_items', to='finance.currency', verbose_name='币种')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_items', to='projects.project', verbose_name='项目')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_items', to='masterdata.supplier', verbose_name='供应商')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '待付款项',
                'verbose_name_plural': '待付款项',
                'db_table': 'payable_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayableSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='本次核销金额')),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payable_settlements', to='finance.bankstatement', verbose_name='银行流水')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('payable_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='finance.payableitem', verbose_name='待付款项')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_settlements', to='finance.payment', verbose_name='付款记录')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '核销记录',
                'verbose_name_plural': '核销记录',
                'db_table': 'payable_settlement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payableitem',
            index=models.Index(fields=['status', 'supplier', 'due_date'], name='payable_ite_status_8af5fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='payableitem',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id'), name='uniq_payable_source'),
        ),
    ]
