# Generated by Django 4.2.9 on 2026-07-06 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_payableitem_payablesettlement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payable_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.payableitem', verbose_name='待付款项'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('AR', '应收款'), ('AP', '应付款'), ('PAYABLE', '待付款项')], max_length=10, verbose_name='付款类型'),
        ),
    ]
