# Generated by Django 4.2.9 on 2026-07-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_payment_payable_item_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='status',
            field=models.CharField(choices=[('PENDING', '待匹配'), ('MATCHED', '已匹配'), ('PARTIAL', '部分核销'), ('IGNORED', '已忽略'), ('ERROR', '匹配错误')], default='PENDING', max_length=20, verbose_name='状态'),
        ),
    ]
