# Generated by Django 4.2.9 on 2026-07-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_alter_bankstatement_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accountpayable',
            index=models.Index(fields=['status', 'due_date'], name='account_pay_status_bceee2_idx'),
        ),
        migrations.AddIndex(
            model_name='accountpayable',
            index=models.Index(fields=['supplier', 'status'], name='account_pay_supplie_13c121_idx'),
        ),
        migrations.AddIndex(
            model_name='accountpayable',
            index=models.Index(fields=['-invoice_date'], name='account_pay_invoice_54f45b_idx'),
        ),
        migrations.AddIndex(
            model_name='accountreceivable',
            index=models.Index(fields=['status', 'due_date'], name='account_rec_status_a521f5_idx'),
        ),
        migrations.AddIndex(
            model_name='accountreceivable',
            index=models.Index(fields=['customer', 'status'], name='account_rec_custome_78390e_idx'),
        ),
        migrations.AddIndex(
            model_name='accountreceivable',
            index=models.Index(fields=['-invoice_date'], name='account_rec_invoice_0ad077_idx'),
        ),
    ]
