# Generated by Django 4.2.9 on 2026-07-09 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_salescontract_so_alter_salescontract_status_and_more'),
        ('finance', '0020_accountpayable_account_pay_status_bceee2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.deliveryorder', verbose_name='关联发货单'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.salesorder', verbose_name='关联销售订单'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='source_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='来源单据ID'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='source_type',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='来源单据类型'),
        ),
    ]
