# Generated by Django 4.2.9 on 2026-07-09 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_invoice_delivery_order_invoice_sales_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrecord',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_collection_records', to='finance.payment', verbose_name='生成的收款单'),
        ),
    ]
