# Generated by Django 4.2.9 on 2026-07-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_collectionrecord_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpayable',
            name='ap_no',
            field=models.CharField(max_length=50, verbose_name='应付单号'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='ar_no',
            field=models.CharField(max_length=50, verbose_name='应收单号'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=50, verbose_name='发票号'),
        ),
        migrations.AlterField(
            model_name='journalvoucher',
            name='voucher_no',
            field=models.CharField(max_length=50, verbose_name='凭证号'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_no',
            field=models.CharField(max_length=50, verbose_name='付款单号'),
        ),
        migrations.AddConstraint(
            model_name='accountpayable',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('ap_no',), name='uq_account_payable_ap_no_active'),
        ),
        migrations.AddConstraint(
            model_name='accountreceivable',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('ar_no',), name='uq_account_receivable_ar_no_active'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('invoice_no',), name='uq_invoice_invoice_no_active'),
        ),
        migrations.AddConstraint(
            model_name='journalvoucher',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('voucher_no',), name='uq_journal_voucher_voucher_no_active'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('payment_no',), name='uq_payment_payment_no_active'),
        ),
    ]
