# Generated by Django 4.2.9 on 2026-01-14 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_bom_integration'),
        ('projects', '0010_add_purchase_request_tracking_to_bom'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbom',
            name='pr_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='已创建采购申请的数量', max_digits=15, verbose_name='采购申请数量'),
        ),
        migrations.AddField(
            model_name='projectbom',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_items', to='purchase.purchaserequest', verbose_name='采购申请'),
        ),
        migrations.AddField(
            model_name='projectbom',
            name='returned_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='退货数量'),
        ),
        migrations.AddField(
            model_name='projectbom',
            name='shipped_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='供应商已发货的数量（在途）', max_digits=15, verbose_name='已发货数量'),
        ),
        migrations.AlterField(
            model_name='projectbom',
            name='order_status',
            field=models.CharField(choices=[('NOT_ORDERED', '未下单'), ('PR_PENDING', '采购申请中'), ('PR_APPROVED', '申请已批准'), ('PARTIAL', '部分下单'), ('ORDERED', '已下单'), ('IN_TRANSIT', '在途'), ('PARTIAL_RECEIVED', '部分收货'), ('RECEIVED', '已收货'), ('RETURNED', '已退货'), ('CANCELLED', '已取消')], default='NOT_ORDERED', max_length=20, verbose_name='下单状态'),
        ),
    ]
