# Generated by Django 4.2.9 on 2025-11-24 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('rfq_no', models.CharField(max_length=50, unique=True, verbose_name='询价单号')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='询价日期')),
                ('response_deadline', models.DateField(verbose_name='报价截止日期')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SENT', '已发送'), ('QUOTED', '已报价'), ('ACCEPTED', '已接受'), ('REJECTED', '已拒绝'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='projects.project', verbose_name='项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '询价单',
                'verbose_name_plural': '询价单',
                'db_table': 'rfq',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='RFQLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='数量')),
                ('required_date', models.DateField(verbose_name='需求日期')),
                ('specifications', models.TextField(blank=True, null=True, verbose_name='规格说明')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_lines', to='masterdata.item', verbose_name='物料')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.rfq', verbose_name='询价单')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '询价单明细',
                'verbose_name_plural': '询价单明细',
                'db_table': 'rfq_line',
            },
        ),
        migrations.CreateModel(
            name='RFQSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='发送日期')),
                ('is_responded', models.BooleanField(default=False, verbose_name='是否已响应')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_rfqs', to='purchase.rfq', verbose_name='询价单')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='masterdata.supplier', verbose_name='供应商')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'RFQ供应商',
                'verbose_name_plural': 'RFQ供应商',
                'db_table': 'rfq_supplier',
                'unique_together': {('rfq', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='SupplierQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('quotation_no', models.CharField(max_length=50, unique=True, verbose_name='报价单号')),
                ('quotation_date', models.DateField(auto_now_add=True, verbose_name='报价日期')),
                ('valid_until', models.DateField(verbose_name='有效期至')),
                ('payment_terms', models.CharField(max_length=200, verbose_name='付款条款')),
                ('delivery_terms', models.CharField(max_length=200, verbose_name='交货条款')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='总金额')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交'), ('ACCEPTED', '已接受'), ('REJECTED', '已拒绝')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('rfq_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='purchase.rfqsupplier', verbose_name='RFQ供应商')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '供应商报价',
                'verbose_name_plural': '供应商报价',
                'db_table': 'supplier_quotation',
                'ordering': ['-quotation_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierQuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='数量')),
                ('lead_time_days', models.IntegerField(verbose_name='交货周期（天）')),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='行金额')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.supplierquotation', verbose_name='供应商报价')),
                ('rfq_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='purchase.rfqline', verbose_name='RFQ明细')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '供应商报价明细',
                'verbose_name_plural': '供应商报价明细',
                'db_table': 'supplier_quotation_line',
            },
        ),
    ]
