# Generated by Django 4.2.9 on 2026-01-13 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_automation_bom_fields'),
        ('purchase', '0004_budgetline_contractexecution_qualificationtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='bom_item',
            field=models.ForeignKey(blank=True, help_text='从BOM生成的采购订单关联', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_lines', to='projects.projectbom', verbose_name='BOM项'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='drawing_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='图纸号'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='function_module',
            field=models.CharField(blank=True, max_length=100, verbose_name='功能模块'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='is_critical',
            field=models.BooleanField(default=False, verbose_name='关键件'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='is_long_lead',
            field=models.BooleanField(default=False, verbose_name='长周期件'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='technical_requirement',
            field=models.TextField(blank=True, verbose_name='技术要求'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='bom_item',
            field=models.ForeignKey(blank=True, help_text='从BOM生成的采购申请关联', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_lines', to='projects.projectbom', verbose_name='BOM项'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='function_module',
            field=models.CharField(blank=True, max_length=100, verbose_name='功能模块'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='is_critical',
            field=models.BooleanField(default=False, verbose_name='关键件'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='is_long_lead',
            field=models.BooleanField(default=False, verbose_name='长周期件'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['bom_item'], name='purchase_or_bom_ite_0ad364_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['is_critical', 'is_long_lead'], name='purchase_or_is_crit_be06be_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestline',
            index=models.Index(fields=['is_critical', 'is_long_lead'], name='purchase_re_is_crit_8fa5ba_idx'),
        ),
    ]
