# Generated by Django 4.2.9 on 2026-07-09 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_supplier_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0006_outsourceinspection_rfqcollaboration_rfqitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('inspection_no', models.CharField(max_length=50, unique=True, verbose_name='检验单号')),
                ('inspected_qty', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='送检数量')),
                ('sample_qty', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='抽样数量')),
                ('defect_qty', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='不良数量')),
                ('result', models.CharField(choices=[('PASS', '合格'), ('FAIL', '不合格'), ('CONDITIONAL', '让步接收(有条件合格)')], default='PASS', max_length=20, verbose_name='检验结果')),
                ('disposition', models.CharField(choices=[('ACCEPT', '接收入库'), ('REJECT', '拒收/退货'), ('CONCESSION', '让步接收')], default='ACCEPT', max_length=20, verbose_name='处置方式')),
                ('inspection_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='检验日期')),
                ('aql', models.CharField(blank=True, max_length=50, verbose_name='AQL/抽样标准')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='purchase.goodsreceipt', verbose_name='收货单')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_inspections', to=settings.AUTH_USER_MODEL, verbose_name='检验员')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_inspections', to='masterdata.item', verbose_name='物料')),
                ('receipt_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='purchase.goodsreceiptline', verbose_name='收货明细')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '来料检验单',
                'verbose_name_plural': '来料检验单',
                'db_table': 'incoming_inspection',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['goods_receipt', 'result'], name='incoming_in_goods_r_48b371_idx'), models.Index(fields=['receipt_line'], name='incoming_in_receipt_ee6a4d_idx'), models.Index(fields=['status', 'result'], name='incoming_in_status_795e4c_idx')],
            },
        ),
    ]
