# Generated by Django 4.2.9 on 2026-07-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_incominginspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceipt',
            name='receipt_no',
            field=models.CharField(max_length=50, verbose_name='收货单号'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_no',
            field=models.CharField(max_length=50, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='request_no',
            field=models.CharField(max_length=50, verbose_name='申请单号'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('receipt_no',), name='uq_goods_receipt_receipt_no_active'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('order_no',), name='uq_purchase_order_order_no_active'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('request_no',), name='uq_purchase_request_request_no_active'),
        ),
    ]
