# Generated by Django 5.2.16 on 2026-08-05 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_alter_goodsreceipt_receipt_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='price_input_mode',
            field=models.CharField(choices=[('EXCLUSIVE', '未税单价'), ('INCLUSIVE', '含税单价')], default='EXCLUSIVE', help_text='整单统一口径。转单时从采购申请继承', max_length=10, verbose_name='单价录入口径'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='source_pr',
            field=models.ForeignKey(blank=True, help_text='由采购申请转换生成时回填,用于在申请列表上反查 PO 号', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_orders', to='purchase.purchaserequest', verbose_name='来源采购申请'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='price_with_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='展示用,不参与金额计算', max_digits=15, verbose_name='含税单价'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='price_input_mode',
            field=models.CharField(choices=[('EXCLUSIVE', '未税单价'), ('INCLUSIVE', '含税单价')], default='EXCLUSIVE', help_text='整单统一口径。含税时按含税单价反算未税单价入账,存量单据保持未税语义', max_length=10, verbose_name='单价录入口径'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='price_with_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='展示用,不参与金额计算', max_digits=15, verbose_name='含税单价'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='单价(未税)'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='预估单价(未税)'),
        ),
    ]
