# Generated by Django 4.2.9 on 2026-01-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dingtalk_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='钉钉用户ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_work_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='企业微信用户ID'),
        ),
    ]
