# Generated by Django 4.2.9 on 2026-01-10 05:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_drawing_equipment_equipmentinstallation_fixture_and_more'),
        ('accounts', '0002_user_dingtalk_id_user_wechat_work_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('overtime_date', models.DateField(verbose_name='加班日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='加班时长(小时)')),
                ('reason', models.TextField(verbose_name='加班原因')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待审批'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtimes', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_requests', to='projects.project', verbose_name='关联项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '加班申请',
                'verbose_name_plural': '加班申请',
                'db_table': 'accounts_overtime_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('leave_type', models.CharField(choices=[('ANNUAL', '年假'), ('SICK', '病假'), ('PERSONAL', '事假'), ('MARRIAGE', '婚假'), ('MATERNITY', '产假'), ('PATERNITY', '陪产假'), ('FUNERAL', '丧假'), ('WORK_INJURY', '工伤假'), ('OTHER', '其他')], default='PERSONAL', max_length=20, verbose_name='请假类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='结束时间')),
                ('days', models.DecimalField(decimal_places=1, default=1, max_digits=5, verbose_name='请假天数')),
                ('reason', models.TextField(verbose_name='请假原因')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待审批'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approval_remarks', models.CharField(blank=True, max_length=500, verbose_name='审批意见')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '请假申请',
                'verbose_name_plural': '请假申请',
                'db_table': 'accounts_leave_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('work_start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='上班时间')),
                ('work_end_time', models.TimeField(default=datetime.time(18, 0), verbose_name='下班时间')),
                ('lunch_start_time', models.TimeField(default=datetime.time(12, 0), verbose_name='午休开始')),
                ('lunch_end_time', models.TimeField(default=datetime.time(13, 0), verbose_name='午休结束')),
                ('flexible_minutes', models.IntegerField(default=0, verbose_name='弹性时间(分钟)')),
                ('late_grace_minutes', models.IntegerField(default=10, verbose_name='迟到宽限(分钟)')),
                ('overtime_min_hours', models.DecimalField(decimal_places=1, default=1, max_digits=4, verbose_name='最小加班时长(小时)')),
                ('weekday_overtime_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=4, verbose_name='工作日加班倍率')),
                ('weekend_overtime_rate', models.DecimalField(decimal_places=2, default=2, max_digits=4, verbose_name='周末加班倍率')),
                ('holiday_overtime_rate', models.DecimalField(decimal_places=2, default=3, max_digits=4, verbose_name='节假日加班倍率')),
                ('workdays', models.JSONField(blank=True, default=list, help_text='0-6: 周一到周日', verbose_name='工作日')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '考勤配置',
                'verbose_name_plural': '考勤配置',
                'db_table': 'accounts_attendance_config',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('attendance_date', models.DateField(verbose_name='考勤日期')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='签退时间')),
                ('check_in_location', models.CharField(blank=True, max_length=200, verbose_name='签到地点')),
                ('check_out_location', models.CharField(blank=True, max_length=200, verbose_name='签退地点')),
                ('status', models.CharField(choices=[('NORMAL', '正常'), ('LATE', '迟到'), ('EARLY', '早退'), ('ABSENT', '缺勤'), ('LEAVE', '请假'), ('OVERTIME', '加班'), ('TRAVEL', '出差'), ('REMOTE', '远程')], default='NORMAL', max_length=20, verbose_name='状态')),
                ('work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='工作时长(小时)')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='加班时长(小时)')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='迟到分钟')),
                ('early_minutes', models.IntegerField(default=0, verbose_name='早退分钟')),
                ('remarks', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
                'db_table': 'accounts_attendance_record',
                'ordering': ['-attendance_date'],
                'unique_together': {('user', 'attendance_date')},
            },
        ),
    ]
