# Generated by Django 4.2.9 on 2026-05-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='data_scope',
            field=models.CharField(choices=[('ALL', '全部数据'), ('DEPARTMENT', '部门数据'), ('SELF', '仅本人数据')], default='ALL', max_length=20, verbose_name='数据权限范围'),
        ),
    ]
