# Generated by Django 4.2.9 on 2026-06-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_role_data_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feishu_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='飞书用户ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dingtalk_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='钉钉用户ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat_work_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='企业微信用户ID'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('wechat_work_id', ''), _negated=True), fields=('wechat_work_id',), name='uniq_user_wechat_work_id'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('dingtalk_id', ''), _negated=True), fields=('dingtalk_id',), name='uniq_user_dingtalk_id'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('feishu_id', ''), _negated=True), fields=('feishu_id',), name='uniq_user_feishu_id'),
        ),
    ]
