# Generated by Django 4.2.9 on 2026-01-10 05:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0004_creditlevel_customerreminder_customerfollowup_and_more'),
        ('sales', '0004_contracttemplate_salescommission_quotetemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinLossReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=100, verbose_name='原因名称')),
                ('reason_type', models.CharField(choices=[('WIN', '赢单'), ('LOSS', '丢单')], max_length=10, verbose_name='原因类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '赢单/丢单原因',
                'verbose_name_plural': '赢单/丢单原因',
                'db_table': 'crm_win_loss_reason',
                'ordering': ['reason_type', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityCloseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('close_type', models.CharField(choices=[('WIN', '赢单'), ('LOSS', '丢单')], max_length=10, verbose_name='关闭类型')),
                ('competitor_name', models.CharField(blank=True, max_length=200, verbose_name='竞争对手名称')),
                ('competitor_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='竞争对手报价')),
                ('our_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='我方报价')),
                ('price_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='价格差异')),
                ('sales_cycle_days', models.IntegerField(blank=True, null=True, verbose_name='销售周期(天)')),
                ('analysis_notes', models.TextField(blank=True, verbose_name='分析备注')),
                ('lessons_learned', models.TextField(blank=True, verbose_name='经验教训')),
                ('customer_feedback', models.TextField(blank=True, verbose_name='客户反馈')),
                ('close_date', models.DateField(default=datetime.date.today, verbose_name='关闭日期')),
                ('competitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_opportunities', to='masterdata.supplier', verbose_name='赢得的竞争对手')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_records', to='sales.opportunity', verbose_name='商机')),
                ('primary_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_records', to='sales.winlossreason', verbose_name='主要原因')),
                ('secondary_reasons', models.ManyToManyField(blank=True, related_name='secondary_close_records', to='sales.winlossreason', verbose_name='次要原因')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '商机关闭记录',
                'verbose_name_plural': '商机关闭记录',
                'db_table': 'crm_opportunity_close_record',
                'ordering': ['-close_date'],
            },
        ),
    ]
