# Generated by Django 4.2.9 on 2026-03-24 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_supplier_settlement_method_alter_item_barcode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0008_reconcile_quote_estimation_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='分层编码')),
                ('name', models.CharField(max_length=50, verbose_name='分层名称')),
                ('r_min', models.IntegerField(default=1, verbose_name='R最小值')),
                ('r_max', models.IntegerField(default=5, verbose_name='R最大值')),
                ('f_min', models.IntegerField(default=1, verbose_name='F最小值')),
                ('f_max', models.IntegerField(default=5, verbose_name='F最大值')),
                ('m_min', models.IntegerField(default=1, verbose_name='M最小值')),
                ('m_max', models.IntegerField(default=5, verbose_name='M最大值')),
                ('color', models.CharField(default='#409EFF', max_length=20, verbose_name='显示颜色')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('strategy', models.TextField(blank=True, verbose_name='营销策略')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '客户分层',
                'verbose_name_plural': '客户分层',
                'db_table': 'sales_customer_segment',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRFMAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('analysis_date', models.DateField(verbose_name='分析日期')),
                ('last_order_date', models.DateField(blank=True, null=True, verbose_name='最近订单日期')),
                ('recency_days', models.IntegerField(default=0, verbose_name='距今天数')),
                ('frequency', models.IntegerField(default=0, verbose_name='订单次数')),
                ('monetary', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='累计金额')),
                ('r_score', models.IntegerField(default=1, verbose_name='R评分')),
                ('f_score', models.IntegerField(default=1, verbose_name='F评分')),
                ('m_score', models.IntegerField(default=1, verbose_name='M评分')),
                ('rfm_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='RFM综合分')),
                ('customer_segment', models.CharField(blank=True, max_length=50, verbose_name='客户分层')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfm_records', to='masterdata.customer', verbose_name='客户')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '客户RFM分析',
                'verbose_name_plural': '客户RFM分析',
                'db_table': 'sales_customer_rfm',
                'ordering': ['-analysis_date', '-rfm_score'],
                'unique_together': {('customer', 'analysis_date')},
            },
        ),
    ]
