# Generated by Django 4.2.9 on 2026-01-10 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='模板编码')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('fields_config', models.JSONField(default=list, help_text='[{"field": "code", "label": "编码", "width": 15}, ...]', verbose_name='字段配置')),
                ('default_filters', models.JSONField(blank=True, default=dict, verbose_name='默认筛选条件')),
                ('default_ordering', models.JSONField(blank=True, default=list, verbose_name='默认排序')),
                ('default_format', models.CharField(choices=[('EXCEL', 'Excel (.xlsx)'), ('CSV', 'CSV (.csv)'), ('PDF', 'PDF (.pdf)'), ('JSON', 'JSON (.json)')], default='EXCEL', max_length=20, verbose_name='默认格式')),
                ('header_style', models.JSONField(blank=True, default=dict, verbose_name='表头样式')),
                ('cell_style', models.JSONField(blank=True, default=dict, verbose_name='单元格样式')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '导出模板',
                'verbose_name_plural': '导出模板',
                'db_table': 'reports_export_template',
                'ordering': ['model_name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('frequency', models.CharField(choices=[('DAILY', '每天'), ('WEEKLY', '每周'), ('MONTHLY', '每月')], default='DAILY', max_length=20, verbose_name='频率')),
                ('execute_time', models.TimeField(verbose_name='执行时间')),
                ('execute_day', models.IntegerField(blank=True, help_text='周几(1-7)或几号(1-31)', null=True, verbose_name='执行日')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='筛选条件')),
                ('recipients', models.JSONField(default=list, verbose_name='收件人邮箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次运行时间')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='下次运行时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_exports', to='reports.exporttemplate', verbose_name='导出模板')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '定时导出',
                'verbose_name_plural': '定时导出',
                'db_table': 'reports_scheduled_export',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('export_name', models.CharField(max_length=200, verbose_name='导出名称')),
                ('export_format', models.CharField(max_length=20, verbose_name='导出格式')),
                ('filters_used', models.JSONField(blank=True, default=dict, verbose_name='使用的筛选条件')),
                ('record_count', models.IntegerField(default=0, verbose_name='导出记录数')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='文件路径')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_histories', to='reports.exporttemplate', verbose_name='导出模板')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '导出历史',
                'verbose_name_plural': '导出历史',
                'db_table': 'reports_export_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
