# Generated by Django 4.2.9 on 2026-05-29 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='模型名称')),
                ('model_type', models.CharField(choices=[('cost_trend', '成本趋势'), ('delivery_risk', '交付风险'), ('capacity_load', '产能负荷'), ('quality_prediction', '质量预测'), ('demand_forecast', '需求预测')], max_length=30, verbose_name='模型类型')),
                ('config', models.JSONField(default=dict, verbose_name='配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '预测模型',
                'verbose_name_plural': '预测模型',
                'db_table': 'reports_prediction_model',
                'ordering': ['model_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('alert_type', models.CharField(choices=[('cost_overrun', '成本超支'), ('schedule_delay', '进度延迟'), ('capacity_shortage', '产能不足'), ('inventory_anomaly', '库存异常'), ('quality_risk', '质量风险'), ('supply_chain_risk', '供应链风险')], max_length=30, verbose_name='告警类型')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], max_length=10, verbose_name='严重程度')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('related_object_type', models.CharField(blank=True, default='', max_length=100, verbose_name='关联对象类型')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('status', models.CharField(choices=[('open', '待处理'), ('acknowledged', '已确认'), ('resolved', '已解决'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态')),
                ('resolution', models.TextField(blank=True, default='', verbose_name='解决方案')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_risk_alerts', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_risk_alerts', to=settings.AUTH_USER_MODEL, verbose_name='解决人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '风险告警',
                'verbose_name_plural': '风险告警',
                'db_table': 'reports_risk_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='报表名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('category', models.CharField(choices=[('sales', '销售'), ('purchase', '采购'), ('inventory', '库存'), ('production', '生产'), ('finance', '财务'), ('project', '项目'), ('quality', '质量'), ('equipment', '设备'), ('comprehensive', '综合')], max_length=20, verbose_name='分类')),
                ('data_source', models.CharField(choices=[('sales_order', '销售订单'), ('purchase_order', '采购订单'), ('stock', '库存'), ('production_order', '生产工单'), ('project', '项目'), ('inspection', '检验'), ('customer', '客户'), ('supplier', '供应商'), ('material', '物料'), ('equipment', '设备'), ('financial_voucher', '财务凭证'), ('quality_record', '质量记录'), ('bom', 'BOM')], max_length=30, verbose_name='数据源')),
                ('config', models.JSONField(default=dict, verbose_name='配置')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统报表')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '报表模板',
                'verbose_name_plural': '报表模板',
                'db_table': 'reports_report_template',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('parameters', models.JSONField(default=dict, verbose_name='参数')),
                ('result_data', models.JSONField(default=dict, verbose_name='结果数据')),
                ('row_count', models.IntegerField(default=0, verbose_name='行数')),
                ('execution_time', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='执行时间(秒)')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_executions_created', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.reporttemplate', verbose_name='报表模板')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '报表执行记录',
                'verbose_name_plural': '报表执行记录',
                'db_table': 'reports_report_execution',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('result_type', models.CharField(max_length=100, verbose_name='结果类型')),
                ('result_data', models.JSONField(default=dict, verbose_name='结果数据')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='置信度')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='有效期至')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='reports.predictionmodel', verbose_name='预测模型')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '预测结果',
                'verbose_name_plural': '预测结果',
                'db_table': 'reports_prediction_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='reports.reporttemplate', verbose_name='报表模板')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '报表收藏',
                'verbose_name_plural': '报表收藏',
                'db_table': 'reports_report_favorite',
                'unique_together': {('user', 'template')},
            },
        ),
    ]
