# Generated by Django 5.2.16 on 2026-09-09 02:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_sales(apps, schema_editor):
    Project = apps.get_model('business', 'Project')
    Sale = apps.get_model('business', 'SalesOrder')
    alias = schema_editor.connection.alias
    for project in Project.objects.using(alias).all().iterator():
        sale = Sale.objects.using(alias).create(
            code=f'LEGACY-{project.pk}', project_id=project.pk, name=project.name,
            customer_id=project.customer_id, manager_id=project.manager_id,
            status='signed' if project.contract_date else 'cancelled' if project.status == 'cancelled' else 'quoted' if project.quote_amount else 'draft',
            requirements=project.requirements, due_date=project.due_date,
            equipment_quantity=project.equipment_quantity, warranty_months=project.warranty_months,
            quote_amount=project.quote_amount, contract_amount=project.contract_amount, contract_date=project.contract_date,
            created_by_id=project.created_by_id, updated_by_id=project.updated_by_id,
            is_deleted=project.is_deleted, deleted_at=project.deleted_at,
        )
        Sale.objects.using(alias).filter(pk=sale.pk).update(created_at=project.created_at, updated_at=project.updated_at)


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_task_service_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('draft', '需求中'), ('quoted', '已报价'), ('signed', '已签约'), ('cancelled', '已取消')], default='draft', max_length=20)),
                ('requirements', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('equipment_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('warranty_months', models.PositiveIntegerField(default=12)),
                ('quote_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('contract_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('contract_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lean_sales_order',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='salesorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='business.partner'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='business.project'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('contract_amount__gte', 0), ('quote_amount__gte', 0)), name='lean_sales_amounts'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('equipment_quantity__gt', 0)), name='lean_sales_equipment_positive'),
        ),
        migrations.RunPython(copy_sales),
        migrations.RemoveConstraint(
            model_name='project',
            name='lean_project_amounts',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contract_amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contract_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='quote_amount',
        ),
    ]
