# Generated by Django 5.2.16 on 2026-09-09 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0009_document_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('date', models.DateField()),
                ('account', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('counterparty', models.CharField(max_length=150)),
                ('reason', models.CharField(max_length=500)),
                ('void_reason', models.CharField(blank=True, max_length=500)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='bank_records',
                        to='business.project',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'lean_bank_record',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reason', models.CharField(max_length=500)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'payment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='bank_matches', to='business.payment'
                    ),
                ),
                (
                    'reversal_of',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='reversal',
                        to='business.bankmatch',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'bank',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='business.bankrecord'
                    ),
                ),
            ],
            options={
                'db_table': 'lean_bank_match',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                (
                    'kind',
                    models.CharField(
                        choices=[('settlement', '业务对账'), ('prepayment', '预付款核准'), ('refund', '退款对账')],
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('draft', '待确认'), ('confirmed', '已确认'), ('void', '已作废')],
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('counterparty_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('basis', models.CharField(blank=True, max_length=500)),
                ('reason', models.CharField(max_length=500)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=500)),
                (
                    'confirmed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'document',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='reconciliations',
                        to='business.document',
                    ),
                ),
                (
                    'entry',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='business.entry'
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'lean_reconciliation',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciliation',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='payments',
                to='business.reconciliation',
            ),
        ),
        migrations.AddConstraint(
            model_name='bankrecord',
            constraint=models.CheckConstraint(
                condition=models.Q(('amount', 0), _negated=True), name='lean_bank_nonzero'
            ),
        ),
        migrations.AddConstraint(
            model_name='bankrecord',
            constraint=models.UniqueConstraint(
                condition=models.Q(('void_reason', '')),
                fields=('account', 'reference'),
                name='lean_bank_reference_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='bankmatch',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('amount__gt', 0), ('reversal_of__isnull', True)),
                    models.Q(('amount__lt', 0), ('reversal_of__isnull', False)),
                    _connector='OR',
                ),
                name='lean_bank_match_direction',
            ),
        ),
        migrations.AddConstraint(
            model_name='reconciliation',
            constraint=models.CheckConstraint(
                condition=models.Q(('approved_amount__gt', 0)), name='lean_reconcile_positive'
            ),
        ),
    ]
