# Generated by Django 5.2.16 on 2026-09-09 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0010_bankrecord_bankmatch_reconciliation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reason', models.CharField(max_length=500)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'returned',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='return_sources',
                        to='business.bankrecord',
                    ),
                ),
                (
                    'reversal_of',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='reversal',
                        to='business.bankoffset',
                    ),
                ),
                (
                    'source',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='returned_funds',
                        to='business.bankrecord',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'lean_bank_offset',
                'ordering': ['-id'],
                'abstract': False,
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('amount__gt', 0), ('reversal_of__isnull', True)),
                            models.Q(('amount__lt', 0), ('reversal_of__isnull', False)),
                            _connector='OR',
                        ),
                        name='lean_bank_offset_direction',
                    )
                ],
            },
        ),
    ]
