# Generated by Django 5.2.16 on 2026-09-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0011_bankoffset'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='payment_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='partner',
            name='payment_term',
            field=models.CharField(
                choices=[
                    ('manual', '指定付款日期'),
                    ('cash', '现付（合格收货日）'),
                    ('month30', '月结30天'),
                    ('month60', '月结60天'),
                    ('month90', '月结90天'),
                    ('month120', '月结120天'),
                    ('custom', '月结自定义天数'),
                ],
                default='manual',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_term',
            field=models.CharField(
                choices=[
                    ('manual', '指定付款日期'),
                    ('cash', '现付（合格收货日）'),
                    ('month30', '月结30天'),
                    ('month60', '月结60天'),
                    ('month90', '月结90天'),
                    ('month120', '月结120天'),
                    ('custom', '月结自定义天数'),
                ],
                default='manual',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
