"""IPD 阶段决策评审(StageGate)基础脚手架测试。

覆盖:gate_no 自动编号、序列化器展示字段、以及 decide 动作记录 Go/Kill/Redirect 决策。
创建 Customer/Project 时关闭 ES 实时索引(override_settings)。
"""

from datetime import date

from django.test import TestCase, override_settings
from rest_framework.test import APIRequestFactory, force_authenticate

from apps.accounts.models import User
from apps.masterdata.models import Customer
from apps.projects.models import Project
from apps.projects.stage_gate import StageGate, StageGateSerializer, StageGateViewSet


@override_settings(ELASTICSEARCH_DSL_AUTOSYNC=False)
class StageGateTest(TestCase):
    def setUp(self):
        self.user = User.objects.create(
            username='ipd_admin', employee_id='IPD1', is_staff=True, is_superuser=True
        )
        self.customer = Customer.objects.create(code='CUST-IPD', name='IPD客户')
        self.project = Project.objects.create(
            code='PRJ-IPD',
            name='IPD项目',
            customer=self.customer,
            manager=self.user,
            start_date='2026-07-01',
            end_date='2026-12-31',
        )
        self.factory = APIRequestFactory()

    def test_gate_no_autogenerated(self):
        gate = StageGate.objects.create(project=self.project, stage='CHARTER', title='立项评审')
        self.assertTrue(gate.gate_no, 'gate_no 应自动生成')
        self.assertEqual(gate.decision, 'PENDING')

    def test_serializer_display_fields(self):
        gate = StageGate.objects.create(project=self.project, stage='DCP', decision='GO')
        data = StageGateSerializer(gate).data
        self.assertEqual(data['project_code'], 'PRJ-IPD')
        self.assertIn('DCP', data['stage_display'])
        self.assertIn('Go', data['decision_display'])

    def test_decide_action_records_decision(self):
        gate = StageGate.objects.create(project=self.project, stage='EVT', title='工程验证门')
        request = self.factory.post(
            f'/api/projects/stage-gates/{gate.id}/decide/',
            {'decision': 'GO', 'summary': '通过'},
            format='json',
        )
        force_authenticate(request, user=self.user)
        response = StageGateViewSet.as_view({'post': 'decide'})(request, pk=gate.id)

        self.assertEqual(response.status_code, 200, getattr(response, 'data', None))
        gate.refresh_from_db()
        self.assertEqual(gate.decision, 'GO')
        self.assertEqual(gate.decision_date, date.today())
        self.assertEqual(gate.summary, '通过')

    def test_decide_rejects_invalid_decision(self):
        gate = StageGate.objects.create(project=self.project, stage='MP')
        request = self.factory.post(
            f'/api/projects/stage-gates/{gate.id}/decide/',
            {'decision': 'MAYBE'},
            format='json',
        )
        force_authenticate(request, user=self.user)
        response = StageGateViewSet.as_view({'post': 'decide'})(request, pk=gate.id)
        self.assertEqual(response.status_code, 400)
