import { test, expect, login, type Page } from './fixtures'

async function read(page: Page, path: string) {
  const token = await page.evaluate(() => localStorage.getItem('access_token'))
  const response = await page.request.get('/api/business/' + path, { headers: { Authorization: `Bearer ${token}` } })
  expect(response.ok(), await response.text()).toBeTruthy()
  return response.json()
}
async function importRows(page: Page, title: string, content: string) {
  await page.getByRole('region', { name: title, exact: true }).getByRole('button', { name: '导入', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '批量导入', exact: true })
  await dialog.locator('input[type=file]').setInputFiles({ name: 'rows.csv', mimeType: 'text/csv', buffer: Buffer.from(content) })
  await expect(dialog.getByRole('button', { name: '确认导入', exact: true })).toBeEnabled()
  const pending = page.waitForResponse(r => r.url().endsWith('/import-confirm/') && r.request().method() === 'POST')
  await dialog.getByRole('button', { name: '确认导入', exact: true }).click()
  const response = await pending
  expect(response.status(), await response.text()).toBe(200)
  await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  return response.json()
}

test('采购按品牌单元类别组合多选，跨页保留勾选且只生成所选BOM行', async ({ page }, info) => {
  await login(page, 'admin', process.env.E2E_ADMIN_PASSWORD!)
  const tag = `BOM${Date.now()}`
  await page.goto('/erp/masterdata')
  const partner = await importRows(page, '客户与供应商', `名称,类型,联系人,电话,地址\n${tag},both,,,\n`)
  const partnerRow = await read(page, `partners/${partner.results[0].id}/`)
  const items = await importRows(page, '物料', '物料编码,名称,规格,单位,品牌,物料类别\n' + Array.from({ length: 13 }, (_, i) => `${tag}-${i},测试件${i},规格,件,${i < 12 ? '品牌A' : '品牌B'},${i < 12 ? 'standard' : 'custom'}`).join('\n'))
  await page.goto('/erp/projects')
  const project = await importRows(page, '项目列表', `名称,客户编码,负责人账号,需求说明,计划交期,设备数量,质保月数,成员账号（分号分隔）\n${tag},${partnerRow.code},admin,,,1,12,\n`)
  const projectId = project.results[0].id
  await page.goto(`/erp/projects/${projectId}`)
  await page.getByRole('tab', { name: 'BOM', exact: true }).click()
  const bom = page.getByRole('region', { name: 'BOM 缺料需求', exact: true })
  await bom.locator('input[type=file]').setInputFiles({ name: 'bom.csv', mimeType: 'text/csv', buffer: Buffer.from('物料编码,数量,变更说明,单元\n' + Array.from({ length: 13 }, (_, i) => `${tag}-${i},1,初版,${i < 12 ? '上料单元' : '检测单元'}`).join('\n')) })
  await bom.getByRole('button', { name: '确认导入', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.locator('[role="dialog"]:visible')).toHaveCount(0)
  await page.goto('/erp/purchases')
  await page.getByRole('button', { name: '从 BOM 多选下单', exact: true }).click()
  const picker = page.getByRole('dialog', { name: '选择 BOM 下单', exact: true })
  await picker.getByLabel('采购项目').selectOption(String(projectId))
  async function filter(label: string, value: string) {
    const input = picker.getByRole('combobox', { name: label, exact: true })
    await expect(input).toBeEnabled()
    await input.focus()
    await input.press('ArrowDown')
    await page.getByRole('option', { name: value, exact: true }).click()
    await page.keyboard.press('Escape')
  }
  await filter('筛选品牌', '品牌A')
  await filter('筛选单元', '上料单元')
  await filter('筛选类别', '标准件')
  await expect(picker.getByRole('status')).toContainText('筛选结果 12 项')
  await picker.getByRole('checkbox', { name: `选择 ${tag}-0`, exact: true }).check()
  await picker.getByRole('button', { name: '下一页', exact: true }).click()
  await picker.getByRole('checkbox', { name: `选择 ${tag}-10`, exact: true }).check()
  await filter('筛选品牌', '品牌B')
  await filter('筛选单元', '检测单元')
  await filter('筛选类别', '非标件')
  await expect(picker.getByRole('status')).toContainText('已选 2 项 · 筛选结果 13 项')
  await picker.getByRole('button', { name: '下一页', exact: true }).click()
  await picker.getByRole('checkbox', { name: `选择 ${tag}-12`, exact: true }).check()
  await page.screenshot({ path: info.outputPath('bom-selection.png'), animations: 'disabled' })
  await picker.getByRole('button', { name: '填写采购单（3 项）', exact: true }).click()
  const order = page.getByRole('dialog', { name: '按缺料采购', exact: true })
  await order.getByLabel('供应商', { exact: true }).selectOption(String(partnerRow.id))
  await order.getByLabel('交期', { exact: true }).fill('2026-09-30')
  for (const field of await order.getByLabel('含税单价（元）', { exact: true }).all()) await field.fill('10')
  const pending = page.waitForResponse(r => r.url().endsWith('/api/business/purchases/') && r.request().method() === 'POST')
  await order.getByRole('button', { name: '保存', exact: true }).click()
  const response = await pending
  expect(response.status(), await response.text()).toBe(201)
  const purchase = await read(page, `purchases/${(await response.json()).id}/`)
  expect(purchase.lines.map((r: { item: number }) => r.item).sort()).toEqual([0, 10, 12].map(i => items.results[i].id).sort())
  expect(purchase.status).toBe('draft')
})
