import { test, expect, login, type Page } from './fixtures'

const dialog = (page: Page) => page.getByRole('dialog')
async function select(page: Page, label: string, text: string) {
  const field = dialog(page).getByLabel(label, { exact: true })
  const value = await field.locator('option').filter({ hasText: text }).last().getAttribute('value')
  await field.selectOption(value!)
}
async function save(page: Page, suffix: string) {
  const pending = page.waitForResponse(r => r.request().method() === 'POST' && r.url().endsWith(suffix))
  await dialog(page).getByRole('button', { name: '保存', exact: true }).click()
  const response = await pending
  expect(response.status(), await response.text()).toBeLessThan(300)
  await expect(dialog(page)).not.toBeVisible()
  return response.json()
}

test('供应商月结默认值带入采购，跨月收货显示各自到期金额', async ({ page }, info) => {
  const name = '月结验收' + Date.now()
  await login(page, 'admin', process.env.E2E_ADMIN_PASSWORD!)
  const token = await page.evaluate(() => localStorage.getItem('access_token'))
  const headers = { Authorization: `Bearer ${token}` }
  async function post(path: string, data: object) {
    const result = await page.request.post('/api/business/' + path, { headers: { ...headers, 'Idempotency-Key': `terms-${Date.now()}-${Math.random()}` }, data })
    expect(result.status(), await result.text()).toBeLessThan(300)
    return result.json()
  }
  // Set up a signed project and material through business APIs; exercise all new fields in the UI.
  const me = await page.request.get('/api/auth/me/', { headers })
  expect(me.ok()).toBeTruthy()
  const user = await me.json()
  const customer = await post('partners/', { name: name + '客户', kind: 'customer' })
  const materialCode = 'CUSTOM-' + Date.now()
  await page.goto('/erp/masterdata?section=items')
  await page.getByRole('button', { name: '新增物料', exact: true }).click()
  await dialog(page).getByLabel('物料编码（留空自动生成）', { exact: true }).fill(materialCode)
  await dialog(page).getByLabel('物料名称', { exact: true }).fill(name + '物料')
  await save(page, '/items/')
  const sale = await post('sales/', { name, customer: customer.id, manager: user.id })
  await post(`sales/${sale.id}/quote/`, { amount: '1000', reason: '验收报价' })
  const signed = await post(`sales/${sale.id}/sign/`, { date: '2026-07-01', manager: user.id, milestones: [{ title: '合同款', amount: '1000', due_date: '2026-12-31' }] })

  await page.goto('/erp/masterdata?section=partners')
  await page.getByRole('button', { name: '新增往来单位', exact: true }).click()
  await dialog(page).getByLabel('单位名称', { exact: true }).fill(name + '供应商')
  await dialog(page).getByLabel('类型', { exact: true }).selectOption('supplier')
  await dialog(page).getByLabel('供应商默认采购账期', { exact: true }).selectOption('month30')
  const supplier = await save(page, '/partners/')
  await page.goto('/erp/purchases')
  await page.getByRole('button', { name: '新建采购', exact: true }).click()
  await select(page, '项目', name)
  await select(page, '供应商', name + '供应商')
  await select(page, '物料', name + '物料')
  await dialog(page).getByLabel('数量', { exact: true }).fill('5')
  await dialog(page).getByLabel('含税单价（元）', { exact: true }).fill('100')
  const purchase = await save(page, '/purchases/')
  const response = await page.request.get(`/api/business/purchases/${purchase.id}/`, { headers })
  const detail = await response.json()
  expect(detail.payment_term).toBe('month30')
  await post(`purchases/${purchase.id}/submit/`, {})
  await post(`purchases/${purchase.id}/approve/`, {})
  await page.goto(`/erp/purchases?resource=purchases&focus=${purchase.id}`)
  await dialog(page).getByRole('button', { name: '预览采购合同', exact: true }).click()
  const contract = page.getByRole('article', { name: '采购合同预览' })
  await expect(contract).toContainText(materialCode)
  await expect(contract).toContainText('月结30天')
  await expect(contract).toContainText('500.00')
  await expect(contract).toContainText(name + '供应商')
  await page.evaluate(() => { window.print = () => { document.body.dataset.printRequested = 'yes' } })
  await page.getByRole('button', { name: '打印 / 另存为 PDF', exact: true }).click()
  await expect(page.locator('body')).toHaveAttribute('data-print-requested', 'yes')
  await page.emulateMedia({ media: 'print' })
  await expect(page.locator('.sidebar')).toBeHidden()
  await expect(page.locator('.contract-toolbar')).toBeHidden()
  await expect(contract).toBeVisible()
  expect(await page.locator('.shell > main').evaluate(el => getComputedStyle(el).backgroundColor)).toBe('rgb(255, 255, 255)')
  expect(await page.locator('html').evaluate(el => getComputedStyle(el).backgroundColor)).toBe('rgb(255, 255, 255)')
  expect(await page.locator('.contract-paper table').evaluate(el => el.getBoundingClientRect().width <= el.parentElement!.getBoundingClientRect().width + 1)).toBeTruthy()
  const pdf = await page.pdf({ path: info.outputPath('purchase-contract.pdf'), preferCSSPageSize: true, printBackground: true })
  expect(pdf.subarray(0, 5).toString()).toBe('%PDF-')
  expect((pdf.toString('latin1').match(/\/Type\s*\/Page\b/g) || []).length).toBe(1)
  await page.emulateMedia({ media: 'screen' })
  await page.screenshot({ path: info.outputPath('purchase-contract.png'), animations: 'disabled', fullPage: true })
  for (const [date, quantity] of [['2026-07-10', '2'], ['2026-08-10', '3']]) {
    await page.goto(`/erp/purchases?resource=purchases&focus=${purchase.id}`)
    await dialog(page).getByRole('button', { name: '收货', exact: true }).click()
    await dialog(page).getByLabel('实际合格收货日期', { exact: true }).fill(date!)
    await dialog(page).getByLabel('数量', { exact: true }).fill(quantity!)
    await dialog(page).getByLabel('原因 / 说明', { exact: true }).fill('按原收货记录核对')
    await save(page, `/purchases/${purchase.id}/receive/`)
  }
  await page.goto(`/erp/projects/${signed.project}?tab=finance&section=entries`)
  const row = page.locator('.el-table__body tr:visible').filter({ hasText: detail.code }).first()
  await row.getByRole('button', { name: '操作 ▾', exact: true }).click()
  await page.getByRole('menuitem', { name: '查看到期明细', exact: true }).click()
  await expect(dialog(page)).toContainText('2026-08-30')
  await expect(dialog(page)).toContainText('2026-09-30')
  await expect(dialog(page)).toContainText('200.00')
  await expect(dialog(page)).toContainText('300.00')
  await expect(dialog(page).getByRole('button', { name: '关闭', exact: true })).toBeInViewport()
  await page.screenshot({ path: info.outputPath('monthly-payment-schedule.png'), animations: 'disabled' })

  const lines = []
  for (let i = 0; i < 30; i++) {
    const material = await post('items/', { name: `${name}多页物料${i}`, code: `PRINT-${Date.now()}-${i}`, specification: '长规格文本用于验证多页合同自动换行及明细完整性', unit: '件' })
    lines.push({ item: material.id, quantity: '1', unit_price: '10' })
  }
  const longOrder = await post('purchases/', { project: signed.project, supplier: supplier.id, due_date: '2026-12-31', note: '补充要求须完整保留。'.repeat(40), lines })
  await page.goto(`/erp/purchases/${longOrder.id}/contract`)
  await expect(page.getByRole('article')).toContainText('草稿 · 未批准')
  await expect(page.getByRole('article')).toContainText('共 30 项物料')
  await expect(page.getByRole('article')).toContainText('质保期为各批货物验收合格之日起一年')
  await expect(page.getByRole('article')).toContainText('违约责任')
  await page.emulateMedia({ media: 'print' })
  const longPdf = await page.pdf({ path: info.outputPath('purchase-contract-summary.pdf'), preferCSSPageSize: true, printBackground: true })
  expect((longPdf.toString('latin1').match(/\/Type\s*\/Page\b/g) || []).length).toBe(1)
  await page.emulateMedia({ media: 'screen' })
  await page.getByRole('button', { name: '查看完整附件' }).click()
  await expect(page.locator('.contract-paper tbody tr')).toHaveCount(30)
  await expect(page.locator('.contract-note')).toHaveText('补充要求须完整保留。'.repeat(40))
  await page.emulateMedia({ media: 'print' })
  const appendixPdf = await page.pdf({ path: info.outputPath('purchase-contract-appendix.pdf'), preferCSSPageSize: true, printBackground: true })
  expect((appendixPdf.toString('latin1').match(/\/Type\s*\/Page\b/g) || []).length).toBeGreaterThan(1)
  await page.emulateMedia({ media: 'screen' })
})
