import { test, expect, expectHttpError, login, type Page, type Locator } from './fixtures'

const dialog = (p: Page) => p.getByRole('dialog')
async function save(p: Page, path: string) {
  const pending = p.waitForResponse(r => r.url().endsWith(path) && r.request().method() === 'POST')
  await dialog(p).getByRole('button', { name: '保存', exact: true }).click()
  const response = await pending
  expect(response.status(), await response.text()).toBeLessThan(300)
  const result = await response.json()
  await expect(dialog(p)).not.toBeVisible()
  return result
}
async function choose(p: Page, label: string, text: string) {
  const field = dialog(p).getByLabel(label, { exact: true })
  const value = await field.locator('option').filter({ hasText: text }).last().getAttribute('value')
  await field.selectOption(value!)
}
async function action(p: Page, row: Locator, name: string) {
  await row.getByRole('button', { name: '操作 ▾', exact: true }).click()
  await p.getByRole('menuitem', { name, exact: true }).click()
  await expect(dialog(p)).toBeVisible()
}
async function read(p: Page, path: string) {
  const token = await p.evaluate(() => localStorage.getItem('access_token'))
  const response = await p.request.get('/api/business/' + path, { headers: { Authorization: `Bearer ${token}` } })
  expect(response.status()).toBe(200)
  return response.json()
}

test('对账差异阻断确认，银行到账认领匹配和多汇退回不重复记账', async ({ page }, info) => {
  test.setTimeout(180000)
  const name = '对账验收' + Date.now(), bankRef = 'BANK-' + Date.now()
  await login(page, 'admin', process.env.E2E_ADMIN_PASSWORD!)
  await page.goto('/erp/masterdata?section=partners')
  await page.getByRole('button', { name: '新增往来单位', exact: true }).click()
  await dialog(page).getByLabel('单位名称', { exact: true }).fill(name)
  await dialog(page).getByLabel('类型', { exact: true }).selectOption('customer')
  await save(page, '/partners/')
  await page.goto('/erp/sales')
  await page.getByRole('button', { name: '新建销售', exact: true }).click()
  await dialog(page).getByLabel('销售名称', { exact: true }).fill(name)
  await choose(page, '客户', name)
  await choose(page, '负责人', '管理员')
  const sale = await save(page, '/sales/')
  const saleRow = page.locator('.el-table__body tr:visible').filter({ hasText: name }).first()
  await action(page, saleRow, '报价')
  await dialog(page).getByLabel('报价金额（元）', { exact: true }).fill('1000')
  await dialog(page).getByLabel('原因 / 说明', { exact: true }).fill('客户确认')
  await save(page, `/sales/${sale.id}/quote/`)
  await action(page, saleRow, '签约')
  const signed = await save(page, `/sales/${sale.id}/sign/`)
  const id = signed.project
  const entry = (await read(page, `entries/?project=${id}`)).results[0]
  await page.goto(`/erp/projects/${id}?tab=finance&section=entries`)
  await action(page, page.locator('.el-table__body tr:visible').filter({ hasText: '合同款' }).first(), '生成对账单')
  await dialog(page).getByLabel('对方确认余额（待退款填负数）', { exact: true }).fill('999')
  await dialog(page).getByLabel('原因 / 说明', { exact: true }).fill('对方账单少一元')
  const statement = await save(page, '/reconciliations/')
  await page.goto(`/erp/finance?section=reconciliations&resource=reconciliations&focus=${statement.id}`)
  await expect(dialog(page)).toContainText('-1.00')
  await expect(dialog(page).getByRole('button', { name: '关闭', exact: true })).toBeInViewport()
  await page.screenshot({ path: info.outputPath('reconciliation-difference.png'), animations: 'disabled' })
  await dialog(page).getByRole('button', { name: '确认对账', exact: true }).click()
  await dialog(page).getByLabel('原因 / 说明', { exact: true }).fill('尝试确认未解决差异')
  expectHttpError(page, `/api/business/reconciliations/${statement.id}/confirm/`, 409)
  const rejected = page.waitForResponse(r => r.url().endsWith(`/reconciliations/${statement.id}/confirm/`))
  await dialog(page).getByRole('button', { name: '保存', exact: true }).click()
  expect((await rejected).status()).toBe(409)
  await expect(dialog(page).getByRole('alert').filter({ hasText: '对账差异未解决' })).toBeVisible()
  await dialog(page).getByRole('button', { name: '取消', exact: true }).click()
  await page.goto(`/erp/finance?section=reconciliations&resource=reconciliations&focus=${statement.id}`)
  await dialog(page).getByRole('button', { name: '作废对账', exact: true }).click()
  await dialog(page).getByLabel('原因 / 说明', { exact: true }).fill('原错误账单作废')
  await save(page, `/reconciliations/${statement.id}/void/`)

  async function bank(amount: string, reference: string) {
    await page.goto('/erp/finance?section=bank')
    await page.getByRole('button', { name: '登记银行到账 / 出账', exact: true }).click()
    for (const [label, value] of [['账户标识', 'BANK-E2E'], ['银行流水号', reference], ['对方户名', name], ['银行金额（收入正数、支出负数）', amount], ['原因 / 说明', '银行真实记录']]) await dialog(page).getByLabel(label!, { exact: true }).fill(value!)
    await choose(page, '已知项目（不确定可留空）', name)
    return (await save(page, '/bank-records/')).id as number
  }
  async function focusBank(bankId: number) {
    await page.goto(`/erp/finance?section=bank&resource=bank-records&focus=${bankId}`)
    await expect(dialog(page)).toBeVisible()
  }
  const incoming = await bank('1100', bankRef)
  expect((await read(page, `entries/${entry.id}/`)).balance).toBe('1000.00')
  await focusBank(incoming)
  await dialog(page).getByRole('button', { name: '认领到账', exact: true }).click()
  await choose(page, '认领款项', name)
  await dialog(page).getByLabel('认领金额（元）', { exact: true }).fill('400')
  await dialog(page).getByLabel('原因 / 说明', { exact: true }).fill('认领首笔合同款')
  await save(page, `/bank-records/${incoming}/allocate/`)
  expect((await read(page, `entries/${entry.id}/`)).balance).toBe('600.00')
  expect((await read(page, `bank-records/${incoming}/`)).remaining_amount).toBe('700.00')
  await page.goto(`/erp/projects/${id}?tab=finance&section=entries`)
  await action(page, page.locator('.el-table__body tr:visible').filter({ hasText: '合同款' }).first(), '登记收付款')
  await dialog(page).getByLabel('结算方式', { exact: true }).selectOption('bank')
  await dialog(page).getByLabel('账户标识', { exact: true }).fill('BANK-E2E')
  await dialog(page).getByLabel('银行流水号', { exact: true }).fill(bankRef)
  await dialog(page).getByLabel('原因 / 说明', { exact: true }).fill('先登记剩余合同款')
  await save(page, `/entries/${entry.id}/pay/`)
  await focusBank(incoming)
  await dialog(page).getByRole('button', { name: '匹配已有收付款', exact: true }).click()
  await choose(page, '已有收付款流水', '600.00')
  await dialog(page).getByLabel('原因 / 说明', { exact: true }).fill('核对已登记流水')
  await save(page, `/bank-records/${incoming}/match/`)
  const outgoing = await bank('-100', bankRef + '-RETURN')
  await focusBank(incoming)
  await dialog(page).getByRole('button', { name: '关联未认领款退回', exact: true }).click()
  await choose(page, '实际退回的银行支出', bankRef + '-RETURN')
  await dialog(page).getByLabel('原因 / 说明', { exact: true }).fill('退回客户多汇的一百元')
  await save(page, `/bank-records/${incoming}/return-unclaimed/`)
  for (const bankId of [incoming, outgoing]) expect((await read(page, `bank-records/${bankId}/`)).remaining_amount).toBe('0.00')
  expect((await read(page, `entries/${entry.id}/`)).balance).toBe('0.00')
  expect((await read(page, `payments/?entry=${entry.id}`)).count).toBe(2)
  await focusBank(incoming)
  await expect(dialog(page).getByRole('button', { name: '认领到账', exact: true })).toHaveCount(0)
  await expect(dialog(page).getByRole('button', { name: '关闭', exact: true })).toBeInViewport()
  await page.screenshot({ path: info.outputPath('bank-reconciled.png'), animations: 'disabled' })
})
