import { test, expect, login, observePage, type Page, type Locator } from './fixtures'

const dialog = (page: Page) => page.getByRole('dialog')
const row = (page: Page, text: string) => page.locator('.el-table__body tr:visible').filter({ hasText: text }).first()
async function choose(page: Page, label: string, text: string) {
  const field = dialog(page).getByLabel(label, { exact: true })
  const value = await field.locator('option').filter({ hasText: text }).last().getAttribute('value')
  await field.selectOption(value!)
}
async function fill(page: Page, label: string, value: string) { await dialog(page).getByLabel(label, { exact: true }).fill(value) }
async function save(page: Page) {
  const pending = page.waitForResponse(r => ['POST', 'PATCH'].includes(r.request().method()) && r.url().includes('/api/'))
  await dialog(page).getByRole('button', { name: '保存', exact: true }).click()
  const response = await pending
  expect(response.status(), await response.text()).toBeLessThan(300)
  await expect(dialog(page)).not.toBeVisible()
}
async function action(page: Page, target: Locator, label: string) {
  await target.getByRole('button', { name: '操作 ▾', exact: true }).click()
  await page.getByRole('menuitem', { name: label, exact: true }).click()
  await expect(dialog(page)).toBeVisible()
}
async function read(page: Page, path: string) {
  const token = await page.evaluate(() => localStorage.getItem('access_token'))
  const response = await page.request.get(`/api/business/${path}`, { headers: { Authorization: `Bearer ${token}` } })
  expect(response.ok()).toBeTruthy()
  return response.json()
}

test('真实角色处理同料多单元、退回修改、隔离品、补充协议和完工估算', async ({ page, browser }, info) => {
  test.setTimeout(240000)
  const suffix = String(Date.now()).slice(-9)
  const password = 'Lean-QA-2026-password'
  await login(page, 'admin', process.env.E2E_ADMIN_PASSWORD!)
  await page.goto('/erp/settings')
  const people: Record<string, Page> = {}
  const errors: string[] = []
  for (const role of ['manager', 'purchaser', 'warehouse', 'finance']) {
    await page.getByRole('button', { name: '新增用户', exact: true }).click()
    await fill(page, '用户名', `${role}review${suffix}`)
    await fill(page, '姓名', `${role}review${suffix}`)
    await dialog(page).getByLabel('角色', { exact: true }).selectOption(role)
    await fill(page, '密码', password)
    await save(page)
    const context = await browser.newContext({ baseURL: info.project.use.baseURL, viewport: info.project.use.viewport, isMobile: info.project.use.isMobile, hasTouch: info.project.use.hasTouch })
    const p = await context.newPage()
    p.setDefaultTimeout(15000)
    observePage(p, errors)
    await login(p, `${role}review${suffix}`, password)
    people[role] = p
  }
  const { manager, purchaser, warehouse, finance } = people
  await purchaser.goto('/erp/masterdata')
  await purchaser.getByRole('button', { name: '新增物料', exact: true }).click()
  await fill(purchaser, '物料名称', `共用传感器${suffix}`)
  await fill(purchaser, '物料编码（留空自动生成）', `REVIEW${suffix}`)
  await save(purchaser)
  for (const kind of ['customer', 'supplier']) {
    await purchaser.getByRole('button', { name: '新增往来单位', exact: true }).click()
    await fill(purchaser, '单位名称', `${kind}${suffix}`)
    await dialog(purchaser).getByLabel('类型', { exact: true }).selectOption(kind)
    await save(purchaser)
  }
  const name = `评审整改${suffix}`
  await manager.goto('/erp/sales')
  await manager.getByRole('button', { name: '新建销售', exact: true }).click()
  await fill(manager, '销售名称', name)
  await choose(manager, '客户', `customer${suffix}`)
  await choose(manager, '负责人', `managerreview${suffix}`)
  await save(manager)
  await action(manager, row(manager, name), '报价')
  await fill(manager, '报价金额（元）', '1000')
  await fill(manager, '原因 / 说明', '确认方案')
  await save(manager)
  await action(manager, row(manager, name), '签约')
  await save(manager)
  const sales = (await read(manager, `sales/?search=${name}`)).results[0]
  const id = sales.project
  await manager.goto(`/erp/projects/${id}`)
  await manager.getByRole('tab', { name: 'BOM', exact: true }).click()
  await manager.locator('input[type=file]').setInputFiles({ name: 'multi-unit.csv', mimeType: 'text/csv', buffer: Buffer.from(`物料编码,数量,变更说明,单元\nREVIEW${suffix},2,初版,上料\nREVIEW${suffix},3,初版,下料\n`) })
  await manager.getByRole('button', { name: '确认导入', exact: true }).click()
  await save(manager)
  expect((await read(manager, `projects/${id}/demand/`)).lines).toHaveLength(2)
  await manager.getByRole('button', { name: '维护 BOM', exact: true }).click()
  await expect(dialog(manager).getByLabel('变更说明', { exact: true })).toHaveCount(2)
  for (const input of await dialog(manager).getByLabel('变更说明', { exact: true }).all()) await input.fill('预览不保存')
  await dialog(manager).getByRole('button', { name: '预览变更影响', exact: true }).click()
  await expect(dialog(manager).getByRole('region', { name: '变更影响预览', exact: true })).toContainText('本次预览可通过')
  await dialog(manager).getByRole('button', { name: '取消', exact: true }).click()
  await manager.getByRole('button', { name: '变更影响与处理', exact: true }).click()
  await expect(dialog(manager)).toContainText('当前最低可改量')
  await dialog(manager).getByRole('button', { name: '关闭', exact: true }).click()
  await purchaser.goto(`/erp/projects/${id}?tab=bom`)
  await purchaser.getByRole('button', { name: '按缺料采购', exact: true }).click()
  await dialog(purchaser).locator('.el-table__body tr').filter({ hasText: '下料' }).getByRole('checkbox').check()
  await purchaser.getByRole('button', { name: '填写采购单（1 项）', exact: true }).click()
  await choose(purchaser, '供应商', `supplier${suffix}`)
  await fill(purchaser, '付款到期日', '2026-12-31')
  await fill(purchaser, '含税单价（元）', '100')
  await save(purchaser)
  const order = (await read(purchaser, `purchases/?project=${id}`)).results[0]
  await purchaser.goto(`/erp/projects/${id}?tab=purchases`)
  await action(purchaser, row(purchaser, order.code), '提交采购')
  await save(purchaser)
  await manager.goto(`/erp/projects/${id}?tab=purchases`)
  await action(manager, row(manager, order.code), '退回修改')
  await fill(manager, '原因 / 说明', '供应商报价复核')
  await save(manager)
  await purchaser.reload()
  await action(purchaser, row(purchaser, order.code), '修改采购')
  await fill(purchaser, '含税单价（元）', '80')
  await fill(purchaser, '原因 / 说明', '确认降价')
  await save(purchaser)
  await action(purchaser, row(purchaser, order.code), '提交采购')
  await save(purchaser)
  await manager.reload()
  await action(manager, row(manager, order.code), '批准采购')
  await save(manager)
  await purchaser.reload()
  await action(purchaser, row(purchaser, order.code), '更新到货计划')
  await fill(purchaser, '承诺到货日期', '2026-09-01')
  await fill(purchaser, '原因 / 说明', '记录供应商原承诺日期并跟进逾期')
  await save(purchaser)
  await purchaser.goto('/erp/workbench')
  await purchaser.getByRole('heading', { name: '采购明细逾期', exact: true }).waitFor()
  await purchaser.getByRole('link').filter({ hasText: order.code }).click()
  await expect(dialog(purchaser).getByRole('heading', { name: '查看明细', exact: true })).toBeVisible()
  await dialog(purchaser).getByRole('button', { name: '关闭', exact: true }).click()
  await warehouse.goto(`/erp/projects/${id}?tab=purchases`)
  await action(warehouse, row(warehouse, order.code), '收货')
  await fill(warehouse, '数量', '1')
  await fill(warehouse, '不合格隔离数量', '2')
  await fill(warehouse, '原因 / 说明', '两件尺寸待复检')
  await save(warehouse)
  await action(warehouse, row(warehouse, order.code), '隔离品合格入库')
  await fill(warehouse, '数量', '1')
  await fill(warehouse, '原因 / 说明', '复检一件合格')
  await save(warehouse)
  await action(warehouse, row(warehouse, order.code), '隔离品退回供应商')
  await fill(warehouse, '原因 / 说明', '剩余一件不合格退回')
  await save(warehouse)
  await purchaser.reload()
  await action(purchaser, row(purchaser, order.code), '取消未收余量')
  await fill(purchaser, '原因 / 说明', '设计变更不再补货')
  await save(purchaser)
  const purchase = await read(purchaser, `purchases/${order.id}/`)
  expect(purchase.lines[0]).toMatchObject({ received_quantity: '2.000', pending_quantity: '0.000', cancelled_quantity: '1.000', unit_price: '80.00' })
  await manager.goto(`/erp/projects/${id}?tab=documents`)
  await manager.getByRole('button', { name: '上传附件', exact: true }).click()
  await dialog(manager).getByLabel('分类', { exact: true }).selectOption('contract')
  await dialog(manager).getByLabel('文件', { exact: true }).setInputFiles({ name: '补充协议.txt', mimeType: 'text/plain', buffer: Buffer.from('双方同意合同减额100元，其他约定不变。') })
  await save(manager)
  const entry = (await read(finance, `entries/?project=${id}&kind=receivable`)).results[0]
  await finance.goto(`/erp/projects/${id}?tab=finance`)
  await action(finance, row(finance, '合同款'), '登记收付款')
  await fill(finance, '原因 / 说明', '原合同款到账')
  await dialog(finance).getByLabel('结算方式', { exact: true }).selectOption('bank')
  await fill(finance, '账户标识', '基本户尾号1234')
  await fill(finance, '银行流水号', `BANK${suffix}`)
  await save(finance)
  await finance.goto(`/erp/projects/${id}?tab=documents`)
  await finance.getByRole('button', { name: '上传附件', exact: true }).click()
  await dialog(finance).getByLabel('分类', { exact: true }).selectOption('receipt')
  await dialog(finance).getByLabel('文件', { exact: true }).setInputFiles({ name: '到账回单.txt', mimeType: 'text/plain', buffer: Buffer.from('银行回单晚于登记到达') })
  await save(finance)
  await finance.goto(`/erp/projects/${id}?tab=finance`)
  await action(finance, row(finance, `BANK${suffix}`), '补录凭证')
  await choose(finance, '凭证（项目附件中上传）', '到账回单.txt')
  await fill(finance, '原因 / 说明', '补到银行回单')
  await save(finance)
  const payment = (await read(finance, `payments/?entry=${entry.id}`)).results[0]
  expect(payment.evidence).toHaveLength(1)
  expect(payment.amount).toBe('1000.00')
  await action(finance, row(finance, `BANK${suffix}`), '查看凭证')
  await expect(dialog(finance)).toContainText('到账回单.txt')
  await dialog(finance).getByRole('button', { name: '关闭', exact: true }).click()
  await manager.goto('/erp/sales')
  await action(manager, row(manager, name), '签订补充协议')
  await fill(manager, '变更后合同总额（元）', '900')
  await fill(manager, '原因 / 说明', '双方确认减额100元')
  await choose(manager, '补充协议附件（先在项目附件上传）', '补充协议.txt')
  const credits = dialog(manager).locator('fieldset').filter({ has: manager.locator('legend').filter({ hasText: '原合同款抵减' }) })
  await credits.getByRole('button', { name: '添加行', exact: true }).click()
  await choose(manager, '原合同款', '合同款')
  await fill(manager, '抵减金额', '100')
  await save(manager)
  expect((await read(finance, `entries/${entry.id}/`)).balance).toBe('-100.00')
  await manager.goto(`/erp/projects/${id}?tab=finance`)
  await manager.getByRole('button', { name: '更新完工估算', exact: true }).click()
  await fill(manager, '预计剩余材料成本（元）', '120')
  await fill(manager, '预计剩余人工成本（元）', '500')
  await fill(manager, '预计剩余费用（元）', '50')
  await fill(manager, '估算依据', '剩余安装与差旅')
  await save(manager)
  expect((await read(manager, `projects/${id}/cost-analysis/`)).forecast_total).toBe('670.00')
  await manager.getByRole('button', { name: '追溯成本明细', exact: true }).click()
  await expect(dialog(manager).getByRole('heading', { name: '成本来源与主要贡献', exact: true })).toBeVisible()
  await expect(dialog(manager)).toContainText('材料领退料')
  await manager.keyboard.press('Escape')
  await expect(dialog(manager)).not.toBeVisible()
  await manager.getByRole('button', { name: '收起项目概览', exact: true }).click()
  await manager.reload()
  await expect(manager.getByRole('button', { name: '展开项目概览', exact: true })).toBeVisible()
  await expect(manager.getByRole('tab', { name: '收付款', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(manager.getByRole('tab', { name: '收付款', exact: true })).toBeInViewport()
  await expect(manager.getByRole('region', { name: '项目收付流水', exact: true })).toContainText(`BANK${suffix}`)
  await manager.screenshot({ path: info.outputPath('review-project-finance.png'), fullPage: true, animations: 'disabled' })
  for (const p of Object.values(people)) await p.context().close()
  expect(errors).toEqual([])
})
