import { test, expect, login } from './fixtures'
import { selectRoles } from './role-helpers'

test('管理员新增销售经理，销售建单报价签约并只读交付回款', async ({ page }, info) => {
  const suffix = String(Date.now())
  const username = `sales${suffix}`
  const password = 'Sales-QA-only-2026-password'
  const customer = `销售客户${suffix}`
  const sale = `销售订单${suffix}`
  const dialog = () => page.locator('[role="dialog"]:visible')
  async function save() {
    const response = page.waitForResponse(r => ['POST', 'PATCH'].includes(r.request().method()) && r.url().includes('/api/'))
    await dialog().getByRole('button', { name: '保存', exact: true }).click()
    const result = await response
    expect(result.status(), await result.text()).toBeLessThan(300)
    await expect(dialog()).toHaveCount(0)
  }
  async function choose(label: string, text: string) {
    const field = dialog().getByLabel(label, { exact: true })
    const value = await field.locator('option').filter({ hasText: text }).last().getAttribute('value')
    await field.selectOption(value!)
  }
  async function action(name: string) {
    await page.locator('.el-table__body tr:visible').filter({ hasText: sale }).first().getByRole('button', { name: '操作 ▾', exact: true }).click()
    await page.getByRole('menuitem', { name, exact: true }).click()
  }
  await login(page, 'admin', process.env.E2E_ADMIN_PASSWORD!)
  await page.goto('/erp/settings')
  await page.getByRole('button', { name: '新增用户', exact: true }).click()
  await dialog().getByLabel('用户名', { exact: true }).fill(username)
  await dialog().getByLabel('姓名', { exact: true }).fill(username)
  await selectRoles(dialog(), ['sales_manager'])
  await dialog().getByLabel('密码', { exact: true }).fill(password)
  await save()
  await login(page, username, password)
  const nav = page.getByRole('navigation', { name: '主导航', includeHidden: true })
  await expect(nav.getByRole('link', { includeHidden: true })).toHaveCount(4)
  await page.goto('/erp/settings?section=users')
  await expect(page.getByRole('tab', { name: '我的账户', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('tab')).toHaveCount(1)
  await expect(page.getByRole('button', { name: '新增用户', exact: true })).toHaveCount(0)
  await expect(page).toHaveURL(/section=account/)
  await page.goto('/erp/masterdata')
  await expect(page.getByRole('region', { name: '客户资料', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '新增往来单位', exact: true }).click()
  await dialog().getByLabel('单位名称', { exact: true }).fill(customer)
  await dialog().getByLabel('类型', { exact: true }).selectOption('customer')
  await save()
  await page.goto('/erp/sales')
  await page.getByRole('button', { name: '新建销售', exact: true }).click()
  await dialog().getByLabel('销售名称', { exact: true }).fill(sale)
  await choose('客户', customer)
  await save()
  await action('附件')
  const attachments = page.getByRole('dialog', { name: /^销售附件/ })
  await attachments.getByRole('button', { name: '上传附件', exact: true }).click()
  const upload = page.getByRole('dialog', { name: '上传销售附件', exact: true })
  const filename = `销售合同${suffix}.txt`
  await upload.getByLabel('文件', { exact: true }).setInputFiles({ name: filename, mimeType: 'text/plain', buffer: Buffer.from('销售合同测试正文') })
  const uploaded = page.waitForResponse(r => r.url().endsWith('/api/business/documents/') && r.request().method() === 'POST')
  await upload.getByRole('button', { name: '保存', exact: true }).click()
  const documentResponse = await uploaded
  expect(documentResponse.status(), await documentResponse.text()).toBe(201)
  const documentId = (await documentResponse.json()).id
  await expect(upload).not.toBeVisible()
  await expect(attachments).toContainText(filename)
  const bounds = await attachments.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  const downloaded = page.waitForEvent('download')
  await attachments.getByRole('button', { name: '下载', exact: true }).click()
  expect((await downloaded).suggestedFilename()).toBe(filename)
  expect((await page.request.get(`/api/business/documents/${documentId}/download/`)).status()).toBe(403)
  await page.screenshot({ path: info.outputPath('sales-attachments.png'), animations: 'disabled' })
  await attachments.getByRole('button', { name: '关闭', exact: true }).click()
  await action('报价')
  await dialog().getByLabel('报价金额（元）', { exact: true }).fill('1000')
  await dialog().getByLabel('原因 / 说明', { exact: true }).fill('客户确认')
  await save()
  await action('签约')
  await expect(dialog().getByLabel('项目负责人', { exact: true }).locator('option').filter({ hasText: username })).toHaveCount(0)
  await choose('项目负责人', '管理员')
  await save()
  const token = await page.evaluate(() => localStorage.getItem('access_token'))
  const doc = await page.request.get(`/api/business/documents/${documentId}/`, { headers: { Authorization: `Bearer ${token}` } })
  expect(doc.status()).toBe(200)
  expect((await doc.json()).project).toBeTruthy()
  await action('交付与回款')
  await expect(dialog()).toContainText('1000.00')
  await expect(dialog()).toContainText('财务处理')
  await page.screenshot({ path: info.outputPath('sales-manager.png'), animations: 'disabled' })
  await dialog().getByRole('button', { name: '关闭', exact: true }).click()
  await page.goto('/erp/purchases')
  await expect(page).toHaveURL(/workbench/)
  await expect(page.getByRole('heading', { name: '我的销售订单', exact: true })).toBeVisible()
})
