import { test, expect, login } from './fixtures'

test('全新安装通过五步向导配置公司人员编号并启用', async ({ page }, testInfo) => {
  test.skip(process.env.E2E_FIRST_INSTALL !== '1', '仅在明确指定的全新隔离安装运行，不重置已有安装。')
  const newPassword = process.env.E2E_SETUP_NEW_PASSWORD
  expect(newPassword, '必须显式提供隔离安装的新密码').toBeTruthy()
  await page.goto('/erp/login')
  await page.getByLabel('用户名', { exact: true }).fill('admin')
  await page.getByLabel('密码', { exact: true }).fill(process.env.E2E_ADMIN_PASSWORD!)
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page).toHaveURL(/\/setup$/)
  await page.reload()
  await expect(page.getByLabel('新密码', { exact: true })).toHaveValue('')
  await page.getByLabel('管理员姓名').fill('向导演练管理员')
  await page.getByLabel('初始密码').fill(process.env.E2E_ADMIN_PASSWORD!)
  await page.getByLabel('新密码', { exact: true }).fill(newPassword!)
  await page.getByLabel('确认新密码').fill(newPassword!)
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByLabel('公司名称').fill('首次安装演练自动化有限公司')
  await page.getByLabel('公司地址').fill('隔离验收园区1号')
  await page.getByLabel('联系电话').fill('010-12345678')
  await page.screenshot({ path: testInfo.outputPath('setup-company.png'), fullPage: true })
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByRole('button', { name: '添加人员' }).click()
  await page.getByLabel('用户名', { exact: true }).fill('setup-buyer')
  await page.getByLabel('姓名', { exact: true }).fill('采购兼仓管')
  await page.getByLabel('登录密码').fill('Setup-Team-Only-20260910-Password')
  await page.getByLabel('成员', { exact: true }).uncheck()
  await page.getByLabel('采购员', { exact: true }).check()
  await page.getByLabel('仓管', { exact: true }).check()
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByLabel('物料前缀', { exact: true }).fill('WL')
  await page.getByRole('button', { name: '下一步' }).click()
  await expect(page.getByText('调整 1 项规则')).toBeVisible()
  await page.getByLabel('我已核对以上资料，确认启用').check()
  await page.screenshot({ path: testInfo.outputPath('setup-confirm.png'), fullPage: true })
  await page.getByRole('button', { name: '完成配置并启用' }).click()
  await expect(page).toHaveURL(/login\?setup=complete/)
  await expect(page.getByText('首次配置完成，请使用新密码登录。')).toBeVisible()
  await login(page, 'admin', newPassword!)
  await page.goto('/erp/setup')
  await expect(page.getByRole('heading', { name: '配置已就绪' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('setup-ready.png'), fullPage: true })
  await page.getByRole('link', { name: '1. 添加客户与供应商' }).click()
  await expect(page).toHaveURL(/masterdata\?section=partners/)
  await expect(page.getByRole('button', { name: '新增往来单位' })).toBeVisible()
  await login(page, 'setup-buyer', 'Setup-Team-Only-20260910-Password')
  await page.goto('/erp/purchases')
  await expect(page.getByRole('heading', { name: '采购', exact: true })).toBeVisible()
  await page.goto('/erp/inventory')
  await expect(page.getByRole('heading', { name: '库存', exact: true })).toBeVisible()
})

test('已安装系统可查看启用指南且不重新初始化', async ({ page }) => {
  test.skip(process.env.E2E_FIRST_INSTALL === '1', '新安装的密码在向导内更换，另行验证现有安装。')
  await login(page, 'admin', process.env.E2E_ADMIN_PASSWORD!)
  await page.goto('/erp/settings')
  await page.getByRole('link', { name: '启用指南' }).click()
  await expect(page.getByRole('heading', { name: '配置已就绪' })).toBeVisible()
  await expect(page.getByRole('button', { name: '完成配置并启用' })).toHaveCount(0)
  await page.getByRole('link', { name: '进入工作台' }).click()
  await expect(page).toHaveURL(/workbench/)
})
