import { readFile } from 'node:fs/promises'
import { test, expect, login } from './fixtures'

test('真实表格预览后导入物料，按筛选导出全部结果和报表', async ({ page }, info) => {
  await login(page, 'admin', process.env.E2E_ADMIN_PASSWORD!)
  await page.goto('/erp/masterdata')
  const panel = page.getByRole('region', { name: '物料', exact: true })
  await page.getByRole('button', { name: '导入', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '批量导入', exact: true })
  const templateEvent = page.waitForEvent('download')
  await dialog.getByRole('button', { name: '下载模板', exact: true }).click()
  const template = await templateEvent
  expect(template.suggestedFilename()).toBe('items-template.xlsx')
  expect((await readFile((await template.path())!)).subarray(0, 2).toString()).toBe('PK')
  const prefix = `IMPORT${Date.now()}`
  await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByLabel('导入导出格式').selectOption('csv')
  await page.getByRole('button', { name: '导入', exact: true }).click()
  const csvDownload = page.waitForEvent('download')
  await dialog.getByRole('button', { name: '下载模板', exact: true }).click()
  const csvTemplate = await csvDownload
  const header = (await readFile((await csvTemplate.path())!, 'utf8')).replace(/^\uFEFF/, '').trim()
  expect(header).toBe('物料编码,物料名称,规格,图号,图档版本,产品编码类别,品牌,物料类别,单位,独立建码原因')
  const csv = header + '\n' + Array.from({ length: 12 }, (_, i) => `${prefix}-${i},导入验收${prefix.slice(6)}-${i},规格A,,,21,品牌B,标准件,台,`).join('\n')
  await dialog.locator('input[type=file]').setInputFiles({ name: 'items.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) })
  await expect(dialog.getByText('共 12 条，确认时再次校验', { exact: false })).toBeVisible()
  const previewTable = dialog.locator('.el-table').last()
  await expect(previewTable.locator('thead')).toContainText('物料名称')
  await expect(previewTable.locator('thead')).toContainText('品牌')
  await expect(previewTable.locator('tbody tr').first()).toContainText('品牌B')
  await expect(dialog.getByRole('button', { name: '确认导入', exact: true })).toBeEnabled()
  await expect(dialog.getByRole('button', { name: '确认导入', exact: true })).toBeInViewport({ ratio: 1 })
  await page.screenshot({ path: info.outputPath('import-preview.png'), animations: 'disabled' })
  await dialog.getByRole('button', { name: '确认导入', exact: true }).click()
  await expect(dialog.getByRole('status')).toContainText('成功导入 12 条记录')
  await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  await panel.getByRole('searchbox').fill(prefix)
  await panel.getByRole('button', { name: '搜索', exact: true }).click()
  await expect(panel.locator('h2 .record-count')).toHaveText('12')
  await expect(panel.locator('.el-table tbody tr').first()).toContainText('品牌B')
  await expect(panel.locator('.el-table tbody tr').first()).toContainText('标准件')
  await expect(panel.locator('.el-table tbody tr').first()).toContainText('台')
  await page.getByLabel('导入导出格式').selectOption('csv')
  const exportedEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出', exact: true }).click()
  const exported = await exportedEvent
  const content = await readFile((await exported.path())!, 'utf8')
  expect(content.match(new RegExp(prefix, 'g'))).toHaveLength(12)
  await page.goto('/erp/reports')
  const reportEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出', exact: true }).click()
  const report = await reportEvent
  expect(report.suggestedFilename()).toBe('reports.xlsx')
  expect((await readFile((await report.path())!)).subarray(0, 2).toString()).toBe('PK')
})
