# Generated by Django 4.2.9 on 2026-07-09 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0009_alter_salescontract_so_alter_salescontract_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesquotation',
            name='parent_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='sales.salesquotation', verbose_name='父版本报价'),
        ),
        migrations.CreateModel(
            name='SalesOrderChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('change_no', models.CharField(max_length=50, unique=True, verbose_name='变更单号')),
                ('change_type', models.CharField(choices=[('ADD', '新增明细'), ('REMOVE', '删除明细'), ('PRICE', '单价调整'), ('QTY', '数量调整'), ('DELIVERY', '交期调整'), ('OTHER', '其他')], max_length=20, verbose_name='变更类型')),
                ('reason', models.TextField(blank=True, verbose_name='变更原因')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待审批'), ('APPROVED', '已审批'), ('REJECTED', '已拒绝')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('change_data', models.JSONField(blank=True, default=dict, verbose_name='变更指令')),
                ('before_data', models.JSONField(blank=True, default=dict, verbose_name='变更前快照')),
                ('after_data', models.JSONField(blank=True, default=dict, verbose_name='变更后快照')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='sales.salesorder', verbose_name='销售订单')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '销售订单变更单',
                'verbose_name_plural': '销售订单变更单',
                'db_table': 'sales_order_change',
                'ordering': ['-created_at'],
            },
        ),
    ]
