# Generated by Django 4.2.9 on 2026-07-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesquotation_parent_quote_salesorderchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='delivery_no',
            field=models.CharField(max_length=50, verbose_name='发货单号'),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='contract_no',
            field=models.CharField(max_length=50, verbose_name='合同编号'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_no',
            field=models.CharField(max_length=50, verbose_name='销售订单号'),
        ),
        migrations.AlterField(
            model_name='salesquotation',
            name='quote_no',
            field=models.CharField(max_length=50, verbose_name='报价单号'),
        ),
        migrations.AddConstraint(
            model_name='deliveryorder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('delivery_no',), name='uq_delivery_order_delivery_no_active'),
        ),
        migrations.AddConstraint(
            model_name='salescontract',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('contract_no',), name='uq_sales_contract_contract_no_active'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('order_no',), name='uq_sales_order_order_no_active'),
        ),
        migrations.AddConstraint(
            model_name='salesquotation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('quote_no',), name='uq_sales_quotation_quote_no_active'),
        ),
    ]
